// Generated by scripts/generate-permissions.mjs. Do not edit manually.

export const Permission = {
  OnboardingManage: "onboarding:manage",
  WorkflowsRead: "workflows:read",
  WorkflowsRun: "workflows:run",
  WorkflowsManage: "workflows:manage",
  IntegrationsRead: "integrations:read",
  IntegrationsManage: "integrations:manage",
  KnowledgeRead: "knowledge:read",
  KnowledgeManage: "knowledge:manage",
  ContextRead: "context:read",
  MemoryRead: "memory:read",
  MemoryManage: "memory:manage",
  OrganizationRead: "organization:read",
  OrganizationManage: "organization:manage",
  SettingsRead: "settings:read",
  SettingsManage: "settings:manage",
} as const;

export type Permission = (typeof Permission)[keyof typeof Permission];

export const allPermissions = Object.values(
  Permission,
) as readonly Permission[];

export const permissionImplications: Readonly<
  Record<Permission, readonly Permission[]>
> = {
  [Permission.OnboardingManage]: [],
  [Permission.WorkflowsRead]: [],
  [Permission.WorkflowsRun]: [Permission.WorkflowsRead],
  [Permission.WorkflowsManage]: [
    Permission.WorkflowsRead,
    Permission.WorkflowsRun,
  ],
  [Permission.IntegrationsRead]: [],
  [Permission.IntegrationsManage]: [Permission.IntegrationsRead],
  [Permission.KnowledgeRead]: [],
  [Permission.KnowledgeManage]: [Permission.KnowledgeRead],
  [Permission.ContextRead]: [],
  [Permission.MemoryRead]: [],
  [Permission.MemoryManage]: [Permission.MemoryRead],
  [Permission.OrganizationRead]: [],
  [Permission.OrganizationManage]: [Permission.OrganizationRead],
  [Permission.SettingsRead]: [],
  [Permission.SettingsManage]: [Permission.SettingsRead],
};

export function isPermission(value: unknown): value is Permission {
  return (
    typeof value === "string" && allPermissions.includes(value as Permission)
  );
}

export function permissionIncludes(
  granted: readonly Permission[],
  required: Permission,
): boolean {
  return (
    granted.includes(required) ||
    granted.some((permission) =>
      permissionImplications[permission].includes(required),
    )
  );
}
