/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as ForbiddenRouteImport } from './routes/forbidden'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as WaitlistRouteImport } from './routes/waitlist'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSplatRouteImport } from './routes/_app/$'
import { Route as AppActivityRouteImport } from './routes/_app/activity'
import { Route as AppManagementRouteImport } from './routes/_app/management'
import { Route as AppMemoryRouteImport } from './routes/_app/memory'
import { Route as AppOrganizationRouteImport } from './routes/_app/organization'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppWorkflowsRouteImport } from './routes/_app/workflows'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as OnboardingCoordinationRouteImport } from './routes/onboarding/coordination'
import { Route as OnboardingMemoryRouteImport } from './routes/onboarding/memory'
import { Route as OnboardingWorkflowsRouteImport } from './routes/onboarding/workflows'
import { Route as OnboardingWorkspaceRouteImport } from './routes/onboarding/workspace'
import { Route as AppManagementAccessRouteImport } from './routes/_app/management/access'
import { Route as AppManagementMembersRouteImport } from './routes/_app/management/members'
import { Route as AppManagementPermissionsRouteImport } from './routes/_app/management/permissions'
import { Route as AppMemoryInvestigationsRouteImport } from './routes/_app/memory/investigations'
import { Route as AppMemoryOrganizationRouteImport } from './routes/_app/memory/organization'
import { Route as AppMemorySourcesRouteImport } from './routes/_app/memory/sources'
import { Route as AppMemoryWorkflowRouteImport } from './routes/_app/memory/workflow'
import { Route as AppOrganizationIndexRouteImport } from './routes/_app/organization/index'
import { Route as AppOrganizationIntegrationsRouteImport } from './routes/_app/organization/integrations'
import { Route as AppOrganizationUnitsRouteImport } from './routes/_app/organization/units'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppSettingsDocumentationRouteImport } from './routes/_app/settings/documentation'
import { Route as AppSettingsNotificationsRouteImport } from './routes/_app/settings/notifications'
import { Route as AppSettingsWorkspaceRouteImport } from './routes/_app/settings/workspace'
import { Route as AppWorkflowsIndexRouteImport } from './routes/_app/workflows/index'
import { Route as AppWorkflowsWorkflowIdRouteImport } from './routes/_app/workflows/$workflowId'
import { Route as AppWorkflowsBlueprintsRouteImport } from './routes/_app/workflows/blueprints'
import { Route as AppWorkflowsNewRouteImport } from './routes/_app/workflows/new'
import { Route as AppWorkflowsPlansRouteImport } from './routes/_app/workflows/plans'
import { Route as AppWorkflowsRunsRouteImport } from './routes/_app/workflows/runs'
import { Route as AppWorkflowsTemplatesRouteImport } from './routes/_app/workflows/templates'
import { Route as AppMemorySourcesIndexRouteImport } from './routes/_app/memory/sources/index'
import { Route as AppMemorySourcesSourceIdRouteImport } from './routes/_app/memory/sources/$sourceId'
import { Route as AppMemorySourcesNewRouteImport } from './routes/_app/memory/sources/new'
import { Route as AppMemoryWorkflowAddRouteImport } from './routes/_app/memory/workflow/add'
import { Route as AppOrganizationIntegrationsIndexRouteImport } from './routes/_app/organization/integrations/index'
import { Route as AppOrganizationIntegrationsIntegrationIdRouteImport } from './routes/_app/organization/integrations/$integrationId'
import { Route as AppOrganizationIntegrationsNewRouteImport } from './routes/_app/organization/integrations/new'
import { Route as AppOrganizationUnitsNewRouteImport } from './routes/_app/organization/units/new'
import { Route as AppWorkflowsBlueprintsBlueprintIdRouteImport } from './routes/_app/workflows/blueprints/$blueprintId'
import { Route as AppWorkflowsDefinitionsWorkflowIdRouteImport } from './routes/_app/workflows/definitions/$workflowId'
import { Route as AppWorkflowsPlansPlanIdRouteImport } from './routes/_app/workflows/plans/$planId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const WaitlistRoute = WaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSplatRoute = AppSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppManagementRoute = AppManagementRouteImport.update({
  id: '/management',
  path: '/management',
  getParentRoute: () => AppRoute,
} as any)
const AppMemoryRoute = AppMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationRoute = AppOrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkflowsRoute = AppWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => AppRoute,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingCoordinationRoute = OnboardingCoordinationRouteImport.update({
  id: '/coordination',
  path: '/coordination',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingMemoryRoute = OnboardingMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingWorkflowsRoute = OnboardingWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingWorkspaceRoute = OnboardingWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => OnboardingRoute,
} as any)
const AppManagementAccessRoute = AppManagementAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => AppManagementRoute,
} as any)
const AppManagementMembersRoute = AppManagementMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppManagementRoute,
} as any)
const AppManagementPermissionsRoute =
  AppManagementPermissionsRouteImport.update({
    id: '/permissions',
    path: '/permissions',
    getParentRoute: () => AppManagementRoute,
  } as any)
const AppMemoryInvestigationsRoute = AppMemoryInvestigationsRouteImport.update({
  id: '/investigations',
  path: '/investigations',
  getParentRoute: () => AppMemoryRoute,
} as any)
const AppMemoryOrganizationRoute = AppMemoryOrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => AppMemoryRoute,
} as any)
const AppMemorySourcesRoute = AppMemorySourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => AppMemoryRoute,
} as any)
const AppMemoryWorkflowRoute = AppMemoryWorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => AppMemoryRoute,
} as any)
const AppOrganizationIndexRoute = AppOrganizationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOrganizationRoute,
} as any)
const AppOrganizationIntegrationsRoute =
  AppOrganizationIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AppOrganizationRoute,
  } as any)
const AppOrganizationUnitsRoute = AppOrganizationUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => AppOrganizationRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsDocumentationRoute =
  AppSettingsDocumentationRouteImport.update({
    id: '/documentation',
    path: '/documentation',
    getParentRoute: () => AppSettingsRoute,
  } as any)
const AppSettingsNotificationsRoute =
  AppSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AppSettingsRoute,
  } as any)
const AppSettingsWorkspaceRoute = AppSettingsWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppWorkflowsIndexRoute = AppWorkflowsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppWorkflowsRoute,
} as any)
const AppWorkflowsWorkflowIdRoute = AppWorkflowsWorkflowIdRouteImport.update({
  id: '/$workflowId',
  path: '/$workflowId',
  getParentRoute: () => AppWorkflowsRoute,
} as any)
const AppWorkflowsBlueprintsRoute = AppWorkflowsBlueprintsRouteImport.update({
  id: '/blueprints',
  path: '/blueprints',
  getParentRoute: () => AppWorkflowsRoute,
} as any)
const AppWorkflowsNewRoute = AppWorkflowsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppWorkflowsRoute,
} as any)
const AppWorkflowsPlansRoute = AppWorkflowsPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AppWorkflowsRoute,
} as any)
const AppWorkflowsRunsRoute = AppWorkflowsRunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => AppWorkflowsRoute,
} as any)
const AppWorkflowsTemplatesRoute = AppWorkflowsTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppWorkflowsRoute,
} as any)
const AppMemorySourcesIndexRoute = AppMemorySourcesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMemorySourcesRoute,
} as any)
const AppMemorySourcesSourceIdRoute =
  AppMemorySourcesSourceIdRouteImport.update({
    id: '/$sourceId',
    path: '/$sourceId',
    getParentRoute: () => AppMemorySourcesRoute,
  } as any)
const AppMemorySourcesNewRoute = AppMemorySourcesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppMemorySourcesRoute,
} as any)
const AppMemoryWorkflowAddRoute = AppMemoryWorkflowAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AppMemoryWorkflowRoute,
} as any)
const AppOrganizationIntegrationsIndexRoute =
  AppOrganizationIntegrationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppOrganizationIntegrationsRoute,
  } as any)
const AppOrganizationIntegrationsIntegrationIdRoute =
  AppOrganizationIntegrationsIntegrationIdRouteImport.update({
    id: '/$integrationId',
    path: '/$integrationId',
    getParentRoute: () => AppOrganizationIntegrationsRoute,
  } as any)
const AppOrganizationIntegrationsNewRoute =
  AppOrganizationIntegrationsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AppOrganizationIntegrationsRoute,
  } as any)
const AppOrganizationUnitsNewRoute = AppOrganizationUnitsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppOrganizationUnitsRoute,
} as any)
const AppWorkflowsBlueprintsBlueprintIdRoute =
  AppWorkflowsBlueprintsBlueprintIdRouteImport.update({
    id: '/$blueprintId',
    path: '/$blueprintId',
    getParentRoute: () => AppWorkflowsBlueprintsRoute,
  } as any)
const AppWorkflowsDefinitionsWorkflowIdRoute =
  AppWorkflowsDefinitionsWorkflowIdRouteImport.update({
    id: '/definitions/$workflowId',
    path: '/definitions/$workflowId',
    getParentRoute: () => AppWorkflowsRoute,
  } as any)
const AppWorkflowsPlansPlanIdRoute = AppWorkflowsPlansPlanIdRouteImport.update({
  id: '/$planId',
  path: '/$planId',
  getParentRoute: () => AppWorkflowsPlansRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/sign-up': typeof SignUpRoute
  '/waitlist': typeof WaitlistRoute
  '/$': typeof AppSplatRoute
  '/activity': typeof AppActivityRoute
  '/management': typeof AppManagementRouteWithChildren
  '/memory': typeof AppMemoryRouteWithChildren
  '/organization': typeof AppOrganizationRouteWithChildren
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/workflows': typeof AppWorkflowsRouteWithChildren
  '/onboarding/coordination': typeof OnboardingCoordinationRoute
  '/onboarding/memory': typeof OnboardingMemoryRoute
  '/onboarding/workflows': typeof OnboardingWorkflowsRoute
  '/onboarding/workspace': typeof OnboardingWorkspaceRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/management/access': typeof AppManagementAccessRoute
  '/management/members': typeof AppManagementMembersRoute
  '/management/permissions': typeof AppManagementPermissionsRoute
  '/memory/investigations': typeof AppMemoryInvestigationsRoute
  '/memory/organization': typeof AppMemoryOrganizationRoute
  '/memory/sources': typeof AppMemorySourcesRouteWithChildren
  '/memory/workflow': typeof AppMemoryWorkflowRouteWithChildren
  '/organization/integrations': typeof AppOrganizationIntegrationsRouteWithChildren
  '/organization/units': typeof AppOrganizationUnitsRouteWithChildren
  '/settings/documentation': typeof AppSettingsDocumentationRoute
  '/settings/notifications': typeof AppSettingsNotificationsRoute
  '/settings/workspace': typeof AppSettingsWorkspaceRoute
  '/workflows/$workflowId': typeof AppWorkflowsWorkflowIdRoute
  '/workflows/blueprints': typeof AppWorkflowsBlueprintsRouteWithChildren
  '/workflows/new': typeof AppWorkflowsNewRoute
  '/workflows/plans': typeof AppWorkflowsPlansRouteWithChildren
  '/workflows/runs': typeof AppWorkflowsRunsRoute
  '/workflows/templates': typeof AppWorkflowsTemplatesRoute
  '/organization/': typeof AppOrganizationIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/workflows/': typeof AppWorkflowsIndexRoute
  '/memory/sources/$sourceId': typeof AppMemorySourcesSourceIdRoute
  '/memory/sources/new': typeof AppMemorySourcesNewRoute
  '/memory/workflow/add': typeof AppMemoryWorkflowAddRoute
  '/organization/integrations/$integrationId': typeof AppOrganizationIntegrationsIntegrationIdRoute
  '/organization/integrations/new': typeof AppOrganizationIntegrationsNewRoute
  '/organization/units/new': typeof AppOrganizationUnitsNewRoute
  '/workflows/blueprints/$blueprintId': typeof AppWorkflowsBlueprintsBlueprintIdRoute
  '/workflows/definitions/$workflowId': typeof AppWorkflowsDefinitionsWorkflowIdRoute
  '/workflows/plans/$planId': typeof AppWorkflowsPlansPlanIdRoute
  '/memory/sources/': typeof AppMemorySourcesIndexRoute
  '/organization/integrations/': typeof AppOrganizationIntegrationsIndexRoute
}
export interface FileRoutesByTo {
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/sign-up': typeof SignUpRoute
  '/waitlist': typeof WaitlistRoute
  '/$': typeof AppSplatRoute
  '/activity': typeof AppActivityRoute
  '/management': typeof AppManagementRouteWithChildren
  '/memory': typeof AppMemoryRouteWithChildren
  '/profile': typeof AppProfileRoute
  '/onboarding/coordination': typeof OnboardingCoordinationRoute
  '/onboarding/memory': typeof OnboardingMemoryRoute
  '/onboarding/workflows': typeof OnboardingWorkflowsRoute
  '/onboarding/workspace': typeof OnboardingWorkspaceRoute
  '/': typeof AppIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/management/access': typeof AppManagementAccessRoute
  '/management/members': typeof AppManagementMembersRoute
  '/management/permissions': typeof AppManagementPermissionsRoute
  '/memory/investigations': typeof AppMemoryInvestigationsRoute
  '/memory/organization': typeof AppMemoryOrganizationRoute
  '/memory/workflow': typeof AppMemoryWorkflowRouteWithChildren
  '/organization/units': typeof AppOrganizationUnitsRouteWithChildren
  '/settings/documentation': typeof AppSettingsDocumentationRoute
  '/settings/notifications': typeof AppSettingsNotificationsRoute
  '/settings/workspace': typeof AppSettingsWorkspaceRoute
  '/workflows/$workflowId': typeof AppWorkflowsWorkflowIdRoute
  '/workflows/blueprints': typeof AppWorkflowsBlueprintsRouteWithChildren
  '/workflows/new': typeof AppWorkflowsNewRoute
  '/workflows/plans': typeof AppWorkflowsPlansRouteWithChildren
  '/workflows/runs': typeof AppWorkflowsRunsRoute
  '/workflows/templates': typeof AppWorkflowsTemplatesRoute
  '/organization': typeof AppOrganizationIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/workflows': typeof AppWorkflowsIndexRoute
  '/memory/sources/$sourceId': typeof AppMemorySourcesSourceIdRoute
  '/memory/sources/new': typeof AppMemorySourcesNewRoute
  '/memory/workflow/add': typeof AppMemoryWorkflowAddRoute
  '/organization/integrations/$integrationId': typeof AppOrganizationIntegrationsIntegrationIdRoute
  '/organization/integrations/new': typeof AppOrganizationIntegrationsNewRoute
  '/organization/units/new': typeof AppOrganizationUnitsNewRoute
  '/workflows/blueprints/$blueprintId': typeof AppWorkflowsBlueprintsBlueprintIdRoute
  '/workflows/definitions/$workflowId': typeof AppWorkflowsDefinitionsWorkflowIdRoute
  '/workflows/plans/$planId': typeof AppWorkflowsPlansPlanIdRoute
  '/memory/sources': typeof AppMemorySourcesIndexRoute
  '/organization/integrations': typeof AppOrganizationIntegrationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/sign-up': typeof SignUpRoute
  '/waitlist': typeof WaitlistRoute
  '/_app/$': typeof AppSplatRoute
  '/_app/activity': typeof AppActivityRoute
  '/_app/management': typeof AppManagementRouteWithChildren
  '/_app/memory': typeof AppMemoryRouteWithChildren
  '/_app/organization': typeof AppOrganizationRouteWithChildren
  '/_app/profile': typeof AppProfileRoute
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/workflows': typeof AppWorkflowsRouteWithChildren
  '/onboarding/coordination': typeof OnboardingCoordinationRoute
  '/onboarding/memory': typeof OnboardingMemoryRoute
  '/onboarding/workflows': typeof OnboardingWorkflowsRoute
  '/onboarding/workspace': typeof OnboardingWorkspaceRoute
  '/_app/': typeof AppIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/_app/management/access': typeof AppManagementAccessRoute
  '/_app/management/members': typeof AppManagementMembersRoute
  '/_app/management/permissions': typeof AppManagementPermissionsRoute
  '/_app/memory/investigations': typeof AppMemoryInvestigationsRoute
  '/_app/memory/organization': typeof AppMemoryOrganizationRoute
  '/_app/memory/sources': typeof AppMemorySourcesRouteWithChildren
  '/_app/memory/workflow': typeof AppMemoryWorkflowRouteWithChildren
  '/_app/organization/integrations': typeof AppOrganizationIntegrationsRouteWithChildren
  '/_app/organization/units': typeof AppOrganizationUnitsRouteWithChildren
  '/_app/settings/documentation': typeof AppSettingsDocumentationRoute
  '/_app/settings/notifications': typeof AppSettingsNotificationsRoute
  '/_app/settings/workspace': typeof AppSettingsWorkspaceRoute
  '/_app/workflows/$workflowId': typeof AppWorkflowsWorkflowIdRoute
  '/_app/workflows/blueprints': typeof AppWorkflowsBlueprintsRouteWithChildren
  '/_app/workflows/new': typeof AppWorkflowsNewRoute
  '/_app/workflows/plans': typeof AppWorkflowsPlansRouteWithChildren
  '/_app/workflows/runs': typeof AppWorkflowsRunsRoute
  '/_app/workflows/templates': typeof AppWorkflowsTemplatesRoute
  '/_app/organization/': typeof AppOrganizationIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/workflows/': typeof AppWorkflowsIndexRoute
  '/_app/memory/sources/$sourceId': typeof AppMemorySourcesSourceIdRoute
  '/_app/memory/sources/new': typeof AppMemorySourcesNewRoute
  '/_app/memory/workflow/add': typeof AppMemoryWorkflowAddRoute
  '/_app/organization/integrations/$integrationId': typeof AppOrganizationIntegrationsIntegrationIdRoute
  '/_app/organization/integrations/new': typeof AppOrganizationIntegrationsNewRoute
  '/_app/organization/units/new': typeof AppOrganizationUnitsNewRoute
  '/_app/workflows/blueprints/$blueprintId': typeof AppWorkflowsBlueprintsBlueprintIdRoute
  '/_app/workflows/definitions/$workflowId': typeof AppWorkflowsDefinitionsWorkflowIdRoute
  '/_app/workflows/plans/$planId': typeof AppWorkflowsPlansPlanIdRoute
  '/_app/memory/sources/': typeof AppMemorySourcesIndexRoute
  '/_app/organization/integrations/': typeof AppOrganizationIntegrationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forbidden'
    | '/login'
    | '/onboarding'
    | '/sign-up'
    | '/waitlist'
    | '/$'
    | '/activity'
    | '/management'
    | '/memory'
    | '/organization'
    | '/profile'
    | '/settings'
    | '/workflows'
    | '/onboarding/coordination'
    | '/onboarding/memory'
    | '/onboarding/workflows'
    | '/onboarding/workspace'
    | '/onboarding/'
    | '/management/access'
    | '/management/members'
    | '/management/permissions'
    | '/memory/investigations'
    | '/memory/organization'
    | '/memory/sources'
    | '/memory/workflow'
    | '/organization/integrations'
    | '/organization/units'
    | '/settings/documentation'
    | '/settings/notifications'
    | '/settings/workspace'
    | '/workflows/$workflowId'
    | '/workflows/blueprints'
    | '/workflows/new'
    | '/workflows/plans'
    | '/workflows/runs'
    | '/workflows/templates'
    | '/organization/'
    | '/settings/'
    | '/workflows/'
    | '/memory/sources/$sourceId'
    | '/memory/sources/new'
    | '/memory/workflow/add'
    | '/organization/integrations/$integrationId'
    | '/organization/integrations/new'
    | '/organization/units/new'
    | '/workflows/blueprints/$blueprintId'
    | '/workflows/definitions/$workflowId'
    | '/workflows/plans/$planId'
    | '/memory/sources/'
    | '/organization/integrations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forbidden'
    | '/login'
    | '/sign-up'
    | '/waitlist'
    | '/$'
    | '/activity'
    | '/management'
    | '/memory'
    | '/profile'
    | '/onboarding/coordination'
    | '/onboarding/memory'
    | '/onboarding/workflows'
    | '/onboarding/workspace'
    | '/'
    | '/onboarding'
    | '/management/access'
    | '/management/members'
    | '/management/permissions'
    | '/memory/investigations'
    | '/memory/organization'
    | '/memory/workflow'
    | '/organization/units'
    | '/settings/documentation'
    | '/settings/notifications'
    | '/settings/workspace'
    | '/workflows/$workflowId'
    | '/workflows/blueprints'
    | '/workflows/new'
    | '/workflows/plans'
    | '/workflows/runs'
    | '/workflows/templates'
    | '/organization'
    | '/settings'
    | '/workflows'
    | '/memory/sources/$sourceId'
    | '/memory/sources/new'
    | '/memory/workflow/add'
    | '/organization/integrations/$integrationId'
    | '/organization/integrations/new'
    | '/organization/units/new'
    | '/workflows/blueprints/$blueprintId'
    | '/workflows/definitions/$workflowId'
    | '/workflows/plans/$planId'
    | '/memory/sources'
    | '/organization/integrations'
  id:
    | '__root__'
    | '/_app'
    | '/forbidden'
    | '/login'
    | '/onboarding'
    | '/sign-up'
    | '/waitlist'
    | '/_app/$'
    | '/_app/activity'
    | '/_app/management'
    | '/_app/memory'
    | '/_app/organization'
    | '/_app/profile'
    | '/_app/settings'
    | '/_app/workflows'
    | '/onboarding/coordination'
    | '/onboarding/memory'
    | '/onboarding/workflows'
    | '/onboarding/workspace'
    | '/_app/'
    | '/onboarding/'
    | '/_app/management/access'
    | '/_app/management/members'
    | '/_app/management/permissions'
    | '/_app/memory/investigations'
    | '/_app/memory/organization'
    | '/_app/memory/sources'
    | '/_app/memory/workflow'
    | '/_app/organization/integrations'
    | '/_app/organization/units'
    | '/_app/settings/documentation'
    | '/_app/settings/notifications'
    | '/_app/settings/workspace'
    | '/_app/workflows/$workflowId'
    | '/_app/workflows/blueprints'
    | '/_app/workflows/new'
    | '/_app/workflows/plans'
    | '/_app/workflows/runs'
    | '/_app/workflows/templates'
    | '/_app/organization/'
    | '/_app/settings/'
    | '/_app/workflows/'
    | '/_app/memory/sources/$sourceId'
    | '/_app/memory/sources/new'
    | '/_app/memory/workflow/add'
    | '/_app/organization/integrations/$integrationId'
    | '/_app/organization/integrations/new'
    | '/_app/organization/units/new'
    | '/_app/workflows/blueprints/$blueprintId'
    | '/_app/workflows/definitions/$workflowId'
    | '/_app/workflows/plans/$planId'
    | '/_app/memory/sources/'
    | '/_app/organization/integrations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ForbiddenRoute: typeof ForbiddenRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRouteWithChildren
  SignUpRoute: typeof SignUpRoute
  WaitlistRoute: typeof WaitlistRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waitlist': {
      id: '/waitlist'
      path: '/waitlist'
      fullPath: '/waitlist'
      preLoaderRoute: typeof WaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$': {
      id: '/_app/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof AppSplatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/activity': {
      id: '/_app/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/management': {
      id: '/_app/management'
      path: '/management'
      fullPath: '/management'
      preLoaderRoute: typeof AppManagementRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/memory': {
      id: '/_app/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof AppMemoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organization': {
      id: '/_app/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof AppOrganizationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workflows': {
      id: '/_app/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof AppWorkflowsRouteImport
      parentRoute: typeof AppRoute
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/coordination': {
      id: '/onboarding/coordination'
      path: '/coordination'
      fullPath: '/onboarding/coordination'
      preLoaderRoute: typeof OnboardingCoordinationRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/memory': {
      id: '/onboarding/memory'
      path: '/memory'
      fullPath: '/onboarding/memory'
      preLoaderRoute: typeof OnboardingMemoryRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/workflows': {
      id: '/onboarding/workflows'
      path: '/workflows'
      fullPath: '/onboarding/workflows'
      preLoaderRoute: typeof OnboardingWorkflowsRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/workspace': {
      id: '/onboarding/workspace'
      path: '/workspace'
      fullPath: '/onboarding/workspace'
      preLoaderRoute: typeof OnboardingWorkspaceRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/_app/management/access': {
      id: '/_app/management/access'
      path: '/access'
      fullPath: '/management/access'
      preLoaderRoute: typeof AppManagementAccessRouteImport
      parentRoute: typeof AppManagementRoute
    }
    '/_app/management/members': {
      id: '/_app/management/members'
      path: '/members'
      fullPath: '/management/members'
      preLoaderRoute: typeof AppManagementMembersRouteImport
      parentRoute: typeof AppManagementRoute
    }
    '/_app/management/permissions': {
      id: '/_app/management/permissions'
      path: '/permissions'
      fullPath: '/management/permissions'
      preLoaderRoute: typeof AppManagementPermissionsRouteImport
      parentRoute: typeof AppManagementRoute
    }
    '/_app/memory/investigations': {
      id: '/_app/memory/investigations'
      path: '/investigations'
      fullPath: '/memory/investigations'
      preLoaderRoute: typeof AppMemoryInvestigationsRouteImport
      parentRoute: typeof AppMemoryRoute
    }
    '/_app/memory/organization': {
      id: '/_app/memory/organization'
      path: '/organization'
      fullPath: '/memory/organization'
      preLoaderRoute: typeof AppMemoryOrganizationRouteImport
      parentRoute: typeof AppMemoryRoute
    }
    '/_app/memory/sources': {
      id: '/_app/memory/sources'
      path: '/sources'
      fullPath: '/memory/sources'
      preLoaderRoute: typeof AppMemorySourcesRouteImport
      parentRoute: typeof AppMemoryRoute
    }
    '/_app/memory/workflow': {
      id: '/_app/memory/workflow'
      path: '/workflow'
      fullPath: '/memory/workflow'
      preLoaderRoute: typeof AppMemoryWorkflowRouteImport
      parentRoute: typeof AppMemoryRoute
    }
    '/_app/organization/': {
      id: '/_app/organization/'
      path: '/'
      fullPath: '/organization/'
      preLoaderRoute: typeof AppOrganizationIndexRouteImport
      parentRoute: typeof AppOrganizationRoute
    }
    '/_app/organization/integrations': {
      id: '/_app/organization/integrations'
      path: '/integrations'
      fullPath: '/organization/integrations'
      preLoaderRoute: typeof AppOrganizationIntegrationsRouteImport
      parentRoute: typeof AppOrganizationRoute
    }
    '/_app/organization/units': {
      id: '/_app/organization/units'
      path: '/units'
      fullPath: '/organization/units'
      preLoaderRoute: typeof AppOrganizationUnitsRouteImport
      parentRoute: typeof AppOrganizationRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/documentation': {
      id: '/_app/settings/documentation'
      path: '/documentation'
      fullPath: '/settings/documentation'
      preLoaderRoute: typeof AppSettingsDocumentationRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/notifications': {
      id: '/_app/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AppSettingsNotificationsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/workspace': {
      id: '/_app/settings/workspace'
      path: '/workspace'
      fullPath: '/settings/workspace'
      preLoaderRoute: typeof AppSettingsWorkspaceRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/workflows/': {
      id: '/_app/workflows/'
      path: '/'
      fullPath: '/workflows/'
      preLoaderRoute: typeof AppWorkflowsIndexRouteImport
      parentRoute: typeof AppWorkflowsRoute
    }
    '/_app/workflows/$workflowId': {
      id: '/_app/workflows/$workflowId'
      path: '/$workflowId'
      fullPath: '/workflows/$workflowId'
      preLoaderRoute: typeof AppWorkflowsWorkflowIdRouteImport
      parentRoute: typeof AppWorkflowsRoute
    }
    '/_app/workflows/blueprints': {
      id: '/_app/workflows/blueprints'
      path: '/blueprints'
      fullPath: '/workflows/blueprints'
      preLoaderRoute: typeof AppWorkflowsBlueprintsRouteImport
      parentRoute: typeof AppWorkflowsRoute
    }
    '/_app/workflows/new': {
      id: '/_app/workflows/new'
      path: '/new'
      fullPath: '/workflows/new'
      preLoaderRoute: typeof AppWorkflowsNewRouteImport
      parentRoute: typeof AppWorkflowsRoute
    }
    '/_app/workflows/plans': {
      id: '/_app/workflows/plans'
      path: '/plans'
      fullPath: '/workflows/plans'
      preLoaderRoute: typeof AppWorkflowsPlansRouteImport
      parentRoute: typeof AppWorkflowsRoute
    }
    '/_app/workflows/runs': {
      id: '/_app/workflows/runs'
      path: '/runs'
      fullPath: '/workflows/runs'
      preLoaderRoute: typeof AppWorkflowsRunsRouteImport
      parentRoute: typeof AppWorkflowsRoute
    }
    '/_app/workflows/templates': {
      id: '/_app/workflows/templates'
      path: '/templates'
      fullPath: '/workflows/templates'
      preLoaderRoute: typeof AppWorkflowsTemplatesRouteImport
      parentRoute: typeof AppWorkflowsRoute
    }
    '/_app/memory/sources/': {
      id: '/_app/memory/sources/'
      path: '/'
      fullPath: '/memory/sources/'
      preLoaderRoute: typeof AppMemorySourcesIndexRouteImport
      parentRoute: typeof AppMemorySourcesRoute
    }
    '/_app/memory/sources/$sourceId': {
      id: '/_app/memory/sources/$sourceId'
      path: '/$sourceId'
      fullPath: '/memory/sources/$sourceId'
      preLoaderRoute: typeof AppMemorySourcesSourceIdRouteImport
      parentRoute: typeof AppMemorySourcesRoute
    }
    '/_app/memory/sources/new': {
      id: '/_app/memory/sources/new'
      path: '/new'
      fullPath: '/memory/sources/new'
      preLoaderRoute: typeof AppMemorySourcesNewRouteImport
      parentRoute: typeof AppMemorySourcesRoute
    }
    '/_app/memory/workflow/add': {
      id: '/_app/memory/workflow/add'
      path: '/add'
      fullPath: '/memory/workflow/add'
      preLoaderRoute: typeof AppMemoryWorkflowAddRouteImport
      parentRoute: typeof AppMemoryWorkflowRoute
    }
    '/_app/organization/integrations/': {
      id: '/_app/organization/integrations/'
      path: '/'
      fullPath: '/organization/integrations/'
      preLoaderRoute: typeof AppOrganizationIntegrationsIndexRouteImport
      parentRoute: typeof AppOrganizationIntegrationsRoute
    }
    '/_app/organization/integrations/$integrationId': {
      id: '/_app/organization/integrations/$integrationId'
      path: '/$integrationId'
      fullPath: '/organization/integrations/$integrationId'
      preLoaderRoute: typeof AppOrganizationIntegrationsIntegrationIdRouteImport
      parentRoute: typeof AppOrganizationIntegrationsRoute
    }
    '/_app/organization/integrations/new': {
      id: '/_app/organization/integrations/new'
      path: '/new'
      fullPath: '/organization/integrations/new'
      preLoaderRoute: typeof AppOrganizationIntegrationsNewRouteImport
      parentRoute: typeof AppOrganizationIntegrationsRoute
    }
    '/_app/organization/units/new': {
      id: '/_app/organization/units/new'
      path: '/new'
      fullPath: '/organization/units/new'
      preLoaderRoute: typeof AppOrganizationUnitsNewRouteImport
      parentRoute: typeof AppOrganizationUnitsRoute
    }
    '/_app/workflows/blueprints/$blueprintId': {
      id: '/_app/workflows/blueprints/$blueprintId'
      path: '/$blueprintId'
      fullPath: '/workflows/blueprints/$blueprintId'
      preLoaderRoute: typeof AppWorkflowsBlueprintsBlueprintIdRouteImport
      parentRoute: typeof AppWorkflowsBlueprintsRoute
    }
    '/_app/workflows/definitions/$workflowId': {
      id: '/_app/workflows/definitions/$workflowId'
      path: '/definitions/$workflowId'
      fullPath: '/workflows/definitions/$workflowId'
      preLoaderRoute: typeof AppWorkflowsDefinitionsWorkflowIdRouteImport
      parentRoute: typeof AppWorkflowsRoute
    }
    '/_app/workflows/plans/$planId': {
      id: '/_app/workflows/plans/$planId'
      path: '/$planId'
      fullPath: '/workflows/plans/$planId'
      preLoaderRoute: typeof AppWorkflowsPlansPlanIdRouteImport
      parentRoute: typeof AppWorkflowsPlansRoute
    }
  }
}

interface AppManagementRouteChildren {
  AppManagementAccessRoute: typeof AppManagementAccessRoute
  AppManagementMembersRoute: typeof AppManagementMembersRoute
  AppManagementPermissionsRoute: typeof AppManagementPermissionsRoute
}

const AppManagementRouteChildren: AppManagementRouteChildren = {
  AppManagementAccessRoute: AppManagementAccessRoute,
  AppManagementMembersRoute: AppManagementMembersRoute,
  AppManagementPermissionsRoute: AppManagementPermissionsRoute,
}

const AppManagementRouteWithChildren = AppManagementRoute._addFileChildren(
  AppManagementRouteChildren,
)

interface AppMemorySourcesRouteChildren {
  AppMemorySourcesSourceIdRoute: typeof AppMemorySourcesSourceIdRoute
  AppMemorySourcesNewRoute: typeof AppMemorySourcesNewRoute
  AppMemorySourcesIndexRoute: typeof AppMemorySourcesIndexRoute
}

const AppMemorySourcesRouteChildren: AppMemorySourcesRouteChildren = {
  AppMemorySourcesSourceIdRoute: AppMemorySourcesSourceIdRoute,
  AppMemorySourcesNewRoute: AppMemorySourcesNewRoute,
  AppMemorySourcesIndexRoute: AppMemorySourcesIndexRoute,
}

const AppMemorySourcesRouteWithChildren =
  AppMemorySourcesRoute._addFileChildren(AppMemorySourcesRouteChildren)

interface AppMemoryWorkflowRouteChildren {
  AppMemoryWorkflowAddRoute: typeof AppMemoryWorkflowAddRoute
}

const AppMemoryWorkflowRouteChildren: AppMemoryWorkflowRouteChildren = {
  AppMemoryWorkflowAddRoute: AppMemoryWorkflowAddRoute,
}

const AppMemoryWorkflowRouteWithChildren =
  AppMemoryWorkflowRoute._addFileChildren(AppMemoryWorkflowRouteChildren)

interface AppMemoryRouteChildren {
  AppMemoryInvestigationsRoute: typeof AppMemoryInvestigationsRoute
  AppMemoryOrganizationRoute: typeof AppMemoryOrganizationRoute
  AppMemorySourcesRoute: typeof AppMemorySourcesRouteWithChildren
  AppMemoryWorkflowRoute: typeof AppMemoryWorkflowRouteWithChildren
}

const AppMemoryRouteChildren: AppMemoryRouteChildren = {
  AppMemoryInvestigationsRoute: AppMemoryInvestigationsRoute,
  AppMemoryOrganizationRoute: AppMemoryOrganizationRoute,
  AppMemorySourcesRoute: AppMemorySourcesRouteWithChildren,
  AppMemoryWorkflowRoute: AppMemoryWorkflowRouteWithChildren,
}

const AppMemoryRouteWithChildren = AppMemoryRoute._addFileChildren(
  AppMemoryRouteChildren,
)

interface AppOrganizationIntegrationsRouteChildren {
  AppOrganizationIntegrationsIntegrationIdRoute: typeof AppOrganizationIntegrationsIntegrationIdRoute
  AppOrganizationIntegrationsNewRoute: typeof AppOrganizationIntegrationsNewRoute
  AppOrganizationIntegrationsIndexRoute: typeof AppOrganizationIntegrationsIndexRoute
}

const AppOrganizationIntegrationsRouteChildren: AppOrganizationIntegrationsRouteChildren =
  {
    AppOrganizationIntegrationsIntegrationIdRoute:
      AppOrganizationIntegrationsIntegrationIdRoute,
    AppOrganizationIntegrationsNewRoute: AppOrganizationIntegrationsNewRoute,
    AppOrganizationIntegrationsIndexRoute:
      AppOrganizationIntegrationsIndexRoute,
  }

const AppOrganizationIntegrationsRouteWithChildren =
  AppOrganizationIntegrationsRoute._addFileChildren(
    AppOrganizationIntegrationsRouteChildren,
  )

interface AppOrganizationUnitsRouteChildren {
  AppOrganizationUnitsNewRoute: typeof AppOrganizationUnitsNewRoute
}

const AppOrganizationUnitsRouteChildren: AppOrganizationUnitsRouteChildren = {
  AppOrganizationUnitsNewRoute: AppOrganizationUnitsNewRoute,
}

const AppOrganizationUnitsRouteWithChildren =
  AppOrganizationUnitsRoute._addFileChildren(AppOrganizationUnitsRouteChildren)

interface AppOrganizationRouteChildren {
  AppOrganizationIntegrationsRoute: typeof AppOrganizationIntegrationsRouteWithChildren
  AppOrganizationUnitsRoute: typeof AppOrganizationUnitsRouteWithChildren
  AppOrganizationIndexRoute: typeof AppOrganizationIndexRoute
}

const AppOrganizationRouteChildren: AppOrganizationRouteChildren = {
  AppOrganizationIntegrationsRoute:
    AppOrganizationIntegrationsRouteWithChildren,
  AppOrganizationUnitsRoute: AppOrganizationUnitsRouteWithChildren,
  AppOrganizationIndexRoute: AppOrganizationIndexRoute,
}

const AppOrganizationRouteWithChildren = AppOrganizationRoute._addFileChildren(
  AppOrganizationRouteChildren,
)

interface AppSettingsRouteChildren {
  AppSettingsDocumentationRoute: typeof AppSettingsDocumentationRoute
  AppSettingsNotificationsRoute: typeof AppSettingsNotificationsRoute
  AppSettingsWorkspaceRoute: typeof AppSettingsWorkspaceRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsDocumentationRoute: AppSettingsDocumentationRoute,
  AppSettingsNotificationsRoute: AppSettingsNotificationsRoute,
  AppSettingsWorkspaceRoute: AppSettingsWorkspaceRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppWorkflowsBlueprintsRouteChildren {
  AppWorkflowsBlueprintsBlueprintIdRoute: typeof AppWorkflowsBlueprintsBlueprintIdRoute
}

const AppWorkflowsBlueprintsRouteChildren: AppWorkflowsBlueprintsRouteChildren =
  {
    AppWorkflowsBlueprintsBlueprintIdRoute:
      AppWorkflowsBlueprintsBlueprintIdRoute,
  }

const AppWorkflowsBlueprintsRouteWithChildren =
  AppWorkflowsBlueprintsRoute._addFileChildren(
    AppWorkflowsBlueprintsRouteChildren,
  )

interface AppWorkflowsPlansRouteChildren {
  AppWorkflowsPlansPlanIdRoute: typeof AppWorkflowsPlansPlanIdRoute
}

const AppWorkflowsPlansRouteChildren: AppWorkflowsPlansRouteChildren = {
  AppWorkflowsPlansPlanIdRoute: AppWorkflowsPlansPlanIdRoute,
}

const AppWorkflowsPlansRouteWithChildren =
  AppWorkflowsPlansRoute._addFileChildren(AppWorkflowsPlansRouteChildren)

interface AppWorkflowsRouteChildren {
  AppWorkflowsWorkflowIdRoute: typeof AppWorkflowsWorkflowIdRoute
  AppWorkflowsBlueprintsRoute: typeof AppWorkflowsBlueprintsRouteWithChildren
  AppWorkflowsNewRoute: typeof AppWorkflowsNewRoute
  AppWorkflowsPlansRoute: typeof AppWorkflowsPlansRouteWithChildren
  AppWorkflowsRunsRoute: typeof AppWorkflowsRunsRoute
  AppWorkflowsTemplatesRoute: typeof AppWorkflowsTemplatesRoute
  AppWorkflowsIndexRoute: typeof AppWorkflowsIndexRoute
  AppWorkflowsDefinitionsWorkflowIdRoute: typeof AppWorkflowsDefinitionsWorkflowIdRoute
}

const AppWorkflowsRouteChildren: AppWorkflowsRouteChildren = {
  AppWorkflowsWorkflowIdRoute: AppWorkflowsWorkflowIdRoute,
  AppWorkflowsBlueprintsRoute: AppWorkflowsBlueprintsRouteWithChildren,
  AppWorkflowsNewRoute: AppWorkflowsNewRoute,
  AppWorkflowsPlansRoute: AppWorkflowsPlansRouteWithChildren,
  AppWorkflowsRunsRoute: AppWorkflowsRunsRoute,
  AppWorkflowsTemplatesRoute: AppWorkflowsTemplatesRoute,
  AppWorkflowsIndexRoute: AppWorkflowsIndexRoute,
  AppWorkflowsDefinitionsWorkflowIdRoute:
    AppWorkflowsDefinitionsWorkflowIdRoute,
}

const AppWorkflowsRouteWithChildren = AppWorkflowsRoute._addFileChildren(
  AppWorkflowsRouteChildren,
)

interface AppRouteChildren {
  AppSplatRoute: typeof AppSplatRoute
  AppActivityRoute: typeof AppActivityRoute
  AppManagementRoute: typeof AppManagementRouteWithChildren
  AppMemoryRoute: typeof AppMemoryRouteWithChildren
  AppOrganizationRoute: typeof AppOrganizationRouteWithChildren
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppWorkflowsRoute: typeof AppWorkflowsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSplatRoute: AppSplatRoute,
  AppActivityRoute: AppActivityRoute,
  AppManagementRoute: AppManagementRouteWithChildren,
  AppMemoryRoute: AppMemoryRouteWithChildren,
  AppOrganizationRoute: AppOrganizationRouteWithChildren,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppWorkflowsRoute: AppWorkflowsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface OnboardingRouteChildren {
  OnboardingCoordinationRoute: typeof OnboardingCoordinationRoute
  OnboardingMemoryRoute: typeof OnboardingMemoryRoute
  OnboardingWorkflowsRoute: typeof OnboardingWorkflowsRoute
  OnboardingWorkspaceRoute: typeof OnboardingWorkspaceRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingCoordinationRoute: OnboardingCoordinationRoute,
  OnboardingMemoryRoute: OnboardingMemoryRoute,
  OnboardingWorkflowsRoute: OnboardingWorkflowsRoute,
  OnboardingWorkspaceRoute: OnboardingWorkspaceRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ForbiddenRoute: ForbiddenRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRouteWithChildren,
  SignUpRoute: SignUpRoute,
  WaitlistRoute: WaitlistRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
