/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as ForbiddenRouteImport } from './routes/forbidden'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as WaitlistRouteImport } from './routes/waitlist'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSplatRouteImport } from './routes/_app/$'
import { Route as AppActivityRouteImport } from './routes/_app/activity'
import { Route as AppManagementRouteImport } from './routes/_app/management'
import { Route as AppOrganizationRouteImport } from './routes/_app/organization'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppWorkflowsRouteImport } from './routes/_app/workflows'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as OnboardingMemoryRouteImport } from './routes/onboarding/memory'
import { Route as OnboardingWorkspaceRouteImport } from './routes/onboarding/workspace'
import { Route as AppManagementAccessRouteImport } from './routes/_app/management/access'
import { Route as AppManagementMembersRouteImport } from './routes/_app/management/members'
import { Route as AppManagementPermissionsRouteImport } from './routes/_app/management/permissions'
import { Route as AppOrganizationIndexRouteImport } from './routes/_app/organization/index'
import { Route as AppOrganizationIntegrationsRouteImport } from './routes/_app/organization/integrations'
import { Route as AppOrganizationInvestigationsRouteImport } from './routes/_app/organization/investigations'
import { Route as AppOrganizationMemoryRouteImport } from './routes/_app/organization/memory'
import { Route as AppOrganizationSourcesRouteImport } from './routes/_app/organization/sources'
import { Route as AppOrganizationUnitsRouteImport } from './routes/_app/organization/units'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppSettingsDocumentationRouteImport } from './routes/_app/settings/documentation'
import { Route as AppSettingsNotificationsRouteImport } from './routes/_app/settings/notifications'
import { Route as AppSettingsWorkspaceRouteImport } from './routes/_app/settings/workspace'
import { Route as AppWorkflowsIndexRouteImport } from './routes/_app/workflows/index'
import { Route as AppWorkflowsWorkflowIdRouteImport } from './routes/_app/workflows/$workflowId'
import { Route as AppWorkflowsBlueprintsRouteImport } from './routes/_app/workflows/blueprints'
import { Route as AppWorkflowsMemoryRouteImport } from './routes/_app/workflows/memory'
import { Route as AppWorkflowsNewRouteImport } from './routes/_app/workflows/new'
import { Route as AppWorkflowsRunsRouteImport } from './routes/_app/workflows/runs'
import { Route as AppWorkflowsTemplatesRouteImport } from './routes/_app/workflows/templates'
import { Route as AppManagementMembersIndexRouteImport } from './routes/_app/management/members/index'
import { Route as AppManagementMembersMemberIdRouteImport } from './routes/_app/management/members/$memberId'
import { Route as AppOrganizationIntegrationsIndexRouteImport } from './routes/_app/organization/integrations/index'
import { Route as AppOrganizationIntegrationsIntegrationIdRouteImport } from './routes/_app/organization/integrations/$integrationId'
import { Route as AppOrganizationIntegrationsCatalogRouteImport } from './routes/_app/organization/integrations/catalog'
import { Route as AppOrganizationIntegrationsNewRouteImport } from './routes/_app/organization/integrations/new'
import { Route as AppOrganizationInvestigationsIndexRouteImport } from './routes/_app/organization/investigations/index'
import { Route as AppOrganizationInvestigationsInvestigationIdRouteImport } from './routes/_app/organization/investigations/$investigationId'
import { Route as AppOrganizationInvestigationsNewRouteImport } from './routes/_app/organization/investigations/new'
import { Route as AppOrganizationSourcesIndexRouteImport } from './routes/_app/organization/sources/index'
import { Route as AppOrganizationSourcesSourceIdRouteImport } from './routes/_app/organization/sources/$sourceId'
import { Route as AppOrganizationSourcesNewRouteImport } from './routes/_app/organization/sources/new'
import { Route as AppOrganizationUnitsNewRouteImport } from './routes/_app/organization/units/new'
import { Route as AppWorkflowsBlueprintsBlueprintIdRouteImport } from './routes/_app/workflows/blueprints/$blueprintId'
import { Route as AppWorkflowsDefinitionsWorkflowIdRouteImport } from './routes/_app/workflows/definitions/$workflowId'
import { Route as AppWorkflowsMemoryAddRouteImport } from './routes/_app/workflows/memory/add'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const WaitlistRoute = WaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSplatRoute = AppSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppManagementRoute = AppManagementRouteImport.update({
  id: '/management',
  path: '/management',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationRoute = AppOrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkflowsRoute = AppWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => AppRoute,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingMemoryRoute = OnboardingMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingWorkspaceRoute = OnboardingWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => OnboardingRoute,
} as any)
const AppManagementAccessRoute = AppManagementAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => AppManagementRoute,
} as any)
const AppManagementMembersRoute = AppManagementMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppManagementRoute,
} as any)
const AppManagementPermissionsRoute =
  AppManagementPermissionsRouteImport.update({
    id: '/permissions',
    path: '/permissions',
    getParentRoute: () => AppManagementRoute,
  } as any)
const AppOrganizationIndexRoute = AppOrganizationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOrganizationRoute,
} as any)
const AppOrganizationIntegrationsRoute =
  AppOrganizationIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AppOrganizationRoute,
  } as any)
const AppOrganizationInvestigationsRoute =
  AppOrganizationInvestigationsRouteImport.update({
    id: '/investigations',
    path: '/investigations',
    getParentRoute: () => AppOrganizationRoute,
  } as any)
const AppOrganizationMemoryRoute = AppOrganizationMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => AppOrganizationRoute,
} as any)
const AppOrganizationSourcesRoute = AppOrganizationSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => AppOrganizationRoute,
} as any)
const AppOrganizationUnitsRoute = AppOrganizationUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => AppOrganizationRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsDocumentationRoute =
  AppSettingsDocumentationRouteImport.update({
    id: '/documentation',
    path: '/documentation',
    getParentRoute: () => AppSettingsRoute,
  } as any)
const AppSettingsNotificationsRoute =
  AppSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AppSettingsRoute,
  } as any)
const AppSettingsWorkspaceRoute = AppSettingsWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppWorkflowsIndexRoute = AppWorkflowsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppWorkflowsRoute,
} as any)
const AppWorkflowsWorkflowIdRoute = AppWorkflowsWorkflowIdRouteImport.update({
  id: '/$workflowId',
  path: '/$workflowId',
  getParentRoute: () => AppWorkflowsRoute,
} as any)
const AppWorkflowsBlueprintsRoute = AppWorkflowsBlueprintsRouteImport.update({
  id: '/blueprints',
  path: '/blueprints',
  getParentRoute: () => AppWorkflowsRoute,
} as any)
const AppWorkflowsMemoryRoute = AppWorkflowsMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => AppWorkflowsRoute,
} as any)
const AppWorkflowsNewRoute = AppWorkflowsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppWorkflowsRoute,
} as any)
const AppWorkflowsRunsRoute = AppWorkflowsRunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => AppWorkflowsRoute,
} as any)
const AppWorkflowsTemplatesRoute = AppWorkflowsTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppWorkflowsRoute,
} as any)
const AppManagementMembersIndexRoute =
  AppManagementMembersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppManagementMembersRoute,
  } as any)
const AppManagementMembersMemberIdRoute =
  AppManagementMembersMemberIdRouteImport.update({
    id: '/$memberId',
    path: '/$memberId',
    getParentRoute: () => AppManagementMembersRoute,
  } as any)
const AppOrganizationIntegrationsIndexRoute =
  AppOrganizationIntegrationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppOrganizationIntegrationsRoute,
  } as any)
const AppOrganizationIntegrationsIntegrationIdRoute =
  AppOrganizationIntegrationsIntegrationIdRouteImport.update({
    id: '/$integrationId',
    path: '/$integrationId',
    getParentRoute: () => AppOrganizationIntegrationsRoute,
  } as any)
const AppOrganizationIntegrationsCatalogRoute =
  AppOrganizationIntegrationsCatalogRouteImport.update({
    id: '/catalog',
    path: '/catalog',
    getParentRoute: () => AppOrganizationIntegrationsRoute,
  } as any)
const AppOrganizationIntegrationsNewRoute =
  AppOrganizationIntegrationsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AppOrganizationIntegrationsRoute,
  } as any)
const AppOrganizationInvestigationsIndexRoute =
  AppOrganizationInvestigationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppOrganizationInvestigationsRoute,
  } as any)
const AppOrganizationInvestigationsInvestigationIdRoute =
  AppOrganizationInvestigationsInvestigationIdRouteImport.update({
    id: '/$investigationId',
    path: '/$investigationId',
    getParentRoute: () => AppOrganizationInvestigationsRoute,
  } as any)
const AppOrganizationInvestigationsNewRoute =
  AppOrganizationInvestigationsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AppOrganizationInvestigationsRoute,
  } as any)
const AppOrganizationSourcesIndexRoute =
  AppOrganizationSourcesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppOrganizationSourcesRoute,
  } as any)
const AppOrganizationSourcesSourceIdRoute =
  AppOrganizationSourcesSourceIdRouteImport.update({
    id: '/$sourceId',
    path: '/$sourceId',
    getParentRoute: () => AppOrganizationSourcesRoute,
  } as any)
const AppOrganizationSourcesNewRoute =
  AppOrganizationSourcesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AppOrganizationSourcesRoute,
  } as any)
const AppOrganizationUnitsNewRoute = AppOrganizationUnitsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppOrganizationUnitsRoute,
} as any)
const AppWorkflowsBlueprintsBlueprintIdRoute =
  AppWorkflowsBlueprintsBlueprintIdRouteImport.update({
    id: '/$blueprintId',
    path: '/$blueprintId',
    getParentRoute: () => AppWorkflowsBlueprintsRoute,
  } as any)
const AppWorkflowsDefinitionsWorkflowIdRoute =
  AppWorkflowsDefinitionsWorkflowIdRouteImport.update({
    id: '/definitions/$workflowId',
    path: '/definitions/$workflowId',
    getParentRoute: () => AppWorkflowsRoute,
  } as any)
const AppWorkflowsMemoryAddRoute = AppWorkflowsMemoryAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AppWorkflowsMemoryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/sign-up': typeof SignUpRoute
  '/waitlist': typeof WaitlistRoute
  '/$': typeof AppSplatRoute
  '/activity': typeof AppActivityRoute
  '/management': typeof AppManagementRouteWithChildren
  '/organization': typeof AppOrganizationRouteWithChildren
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/workflows': typeof AppWorkflowsRouteWithChildren
  '/onboarding/memory': typeof OnboardingMemoryRoute
  '/onboarding/workspace': typeof OnboardingWorkspaceRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/management/access': typeof AppManagementAccessRoute
  '/management/members': typeof AppManagementMembersRouteWithChildren
  '/management/permissions': typeof AppManagementPermissionsRoute
  '/organization/integrations': typeof AppOrganizationIntegrationsRouteWithChildren
  '/organization/investigations': typeof AppOrganizationInvestigationsRouteWithChildren
  '/organization/memory': typeof AppOrganizationMemoryRoute
  '/organization/sources': typeof AppOrganizationSourcesRouteWithChildren
  '/organization/units': typeof AppOrganizationUnitsRouteWithChildren
  '/settings/documentation': typeof AppSettingsDocumentationRoute
  '/settings/notifications': typeof AppSettingsNotificationsRoute
  '/settings/workspace': typeof AppSettingsWorkspaceRoute
  '/workflows/$workflowId': typeof AppWorkflowsWorkflowIdRoute
  '/workflows/blueprints': typeof AppWorkflowsBlueprintsRouteWithChildren
  '/workflows/memory': typeof AppWorkflowsMemoryRouteWithChildren
  '/workflows/new': typeof AppWorkflowsNewRoute
  '/workflows/runs': typeof AppWorkflowsRunsRoute
  '/workflows/templates': typeof AppWorkflowsTemplatesRoute
  '/organization/': typeof AppOrganizationIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/workflows/': typeof AppWorkflowsIndexRoute
  '/management/members/$memberId': typeof AppManagementMembersMemberIdRoute
  '/organization/integrations/$integrationId': typeof AppOrganizationIntegrationsIntegrationIdRoute
  '/organization/integrations/catalog': typeof AppOrganizationIntegrationsCatalogRoute
  '/organization/integrations/new': typeof AppOrganizationIntegrationsNewRoute
  '/organization/investigations/$investigationId': typeof AppOrganizationInvestigationsInvestigationIdRoute
  '/organization/investigations/new': typeof AppOrganizationInvestigationsNewRoute
  '/organization/sources/$sourceId': typeof AppOrganizationSourcesSourceIdRoute
  '/organization/sources/new': typeof AppOrganizationSourcesNewRoute
  '/organization/units/new': typeof AppOrganizationUnitsNewRoute
  '/workflows/blueprints/$blueprintId': typeof AppWorkflowsBlueprintsBlueprintIdRoute
  '/workflows/definitions/$workflowId': typeof AppWorkflowsDefinitionsWorkflowIdRoute
  '/workflows/memory/add': typeof AppWorkflowsMemoryAddRoute
  '/management/members/': typeof AppManagementMembersIndexRoute
  '/organization/integrations/': typeof AppOrganizationIntegrationsIndexRoute
  '/organization/investigations/': typeof AppOrganizationInvestigationsIndexRoute
  '/organization/sources/': typeof AppOrganizationSourcesIndexRoute
}
export interface FileRoutesByTo {
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/sign-up': typeof SignUpRoute
  '/waitlist': typeof WaitlistRoute
  '/$': typeof AppSplatRoute
  '/activity': typeof AppActivityRoute
  '/management': typeof AppManagementRouteWithChildren
  '/profile': typeof AppProfileRoute
  '/onboarding/memory': typeof OnboardingMemoryRoute
  '/onboarding/workspace': typeof OnboardingWorkspaceRoute
  '/': typeof AppIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/management/access': typeof AppManagementAccessRoute
  '/management/permissions': typeof AppManagementPermissionsRoute
  '/organization/memory': typeof AppOrganizationMemoryRoute
  '/organization/units': typeof AppOrganizationUnitsRouteWithChildren
  '/settings/documentation': typeof AppSettingsDocumentationRoute
  '/settings/notifications': typeof AppSettingsNotificationsRoute
  '/settings/workspace': typeof AppSettingsWorkspaceRoute
  '/workflows/$workflowId': typeof AppWorkflowsWorkflowIdRoute
  '/workflows/blueprints': typeof AppWorkflowsBlueprintsRouteWithChildren
  '/workflows/memory': typeof AppWorkflowsMemoryRouteWithChildren
  '/workflows/new': typeof AppWorkflowsNewRoute
  '/workflows/runs': typeof AppWorkflowsRunsRoute
  '/workflows/templates': typeof AppWorkflowsTemplatesRoute
  '/organization': typeof AppOrganizationIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/workflows': typeof AppWorkflowsIndexRoute
  '/management/members/$memberId': typeof AppManagementMembersMemberIdRoute
  '/organization/integrations/$integrationId': typeof AppOrganizationIntegrationsIntegrationIdRoute
  '/organization/integrations/catalog': typeof AppOrganizationIntegrationsCatalogRoute
  '/organization/integrations/new': typeof AppOrganizationIntegrationsNewRoute
  '/organization/investigations/$investigationId': typeof AppOrganizationInvestigationsInvestigationIdRoute
  '/organization/investigations/new': typeof AppOrganizationInvestigationsNewRoute
  '/organization/sources/$sourceId': typeof AppOrganizationSourcesSourceIdRoute
  '/organization/sources/new': typeof AppOrganizationSourcesNewRoute
  '/organization/units/new': typeof AppOrganizationUnitsNewRoute
  '/workflows/blueprints/$blueprintId': typeof AppWorkflowsBlueprintsBlueprintIdRoute
  '/workflows/definitions/$workflowId': typeof AppWorkflowsDefinitionsWorkflowIdRoute
  '/workflows/memory/add': typeof AppWorkflowsMemoryAddRoute
  '/management/members': typeof AppManagementMembersIndexRoute
  '/organization/integrations': typeof AppOrganizationIntegrationsIndexRoute
  '/organization/investigations': typeof AppOrganizationInvestigationsIndexRoute
  '/organization/sources': typeof AppOrganizationSourcesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/sign-up': typeof SignUpRoute
  '/waitlist': typeof WaitlistRoute
  '/_app/$': typeof AppSplatRoute
  '/_app/activity': typeof AppActivityRoute
  '/_app/management': typeof AppManagementRouteWithChildren
  '/_app/organization': typeof AppOrganizationRouteWithChildren
  '/_app/profile': typeof AppProfileRoute
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/workflows': typeof AppWorkflowsRouteWithChildren
  '/onboarding/memory': typeof OnboardingMemoryRoute
  '/onboarding/workspace': typeof OnboardingWorkspaceRoute
  '/_app/': typeof AppIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/_app/management/access': typeof AppManagementAccessRoute
  '/_app/management/members': typeof AppManagementMembersRouteWithChildren
  '/_app/management/permissions': typeof AppManagementPermissionsRoute
  '/_app/organization/integrations': typeof AppOrganizationIntegrationsRouteWithChildren
  '/_app/organization/investigations': typeof AppOrganizationInvestigationsRouteWithChildren
  '/_app/organization/memory': typeof AppOrganizationMemoryRoute
  '/_app/organization/sources': typeof AppOrganizationSourcesRouteWithChildren
  '/_app/organization/units': typeof AppOrganizationUnitsRouteWithChildren
  '/_app/settings/documentation': typeof AppSettingsDocumentationRoute
  '/_app/settings/notifications': typeof AppSettingsNotificationsRoute
  '/_app/settings/workspace': typeof AppSettingsWorkspaceRoute
  '/_app/workflows/$workflowId': typeof AppWorkflowsWorkflowIdRoute
  '/_app/workflows/blueprints': typeof AppWorkflowsBlueprintsRouteWithChildren
  '/_app/workflows/memory': typeof AppWorkflowsMemoryRouteWithChildren
  '/_app/workflows/new': typeof AppWorkflowsNewRoute
  '/_app/workflows/runs': typeof AppWorkflowsRunsRoute
  '/_app/workflows/templates': typeof AppWorkflowsTemplatesRoute
  '/_app/organization/': typeof AppOrganizationIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/workflows/': typeof AppWorkflowsIndexRoute
  '/_app/management/members/$memberId': typeof AppManagementMembersMemberIdRoute
  '/_app/organization/integrations/$integrationId': typeof AppOrganizationIntegrationsIntegrationIdRoute
  '/_app/organization/integrations/catalog': typeof AppOrganizationIntegrationsCatalogRoute
  '/_app/organization/integrations/new': typeof AppOrganizationIntegrationsNewRoute
  '/_app/organization/investigations/$investigationId': typeof AppOrganizationInvestigationsInvestigationIdRoute
  '/_app/organization/investigations/new': typeof AppOrganizationInvestigationsNewRoute
  '/_app/organization/sources/$sourceId': typeof AppOrganizationSourcesSourceIdRoute
  '/_app/organization/sources/new': typeof AppOrganizationSourcesNewRoute
  '/_app/organization/units/new': typeof AppOrganizationUnitsNewRoute
  '/_app/workflows/blueprints/$blueprintId': typeof AppWorkflowsBlueprintsBlueprintIdRoute
  '/_app/workflows/definitions/$workflowId': typeof AppWorkflowsDefinitionsWorkflowIdRoute
  '/_app/workflows/memory/add': typeof AppWorkflowsMemoryAddRoute
  '/_app/management/members/': typeof AppManagementMembersIndexRoute
  '/_app/organization/integrations/': typeof AppOrganizationIntegrationsIndexRoute
  '/_app/organization/investigations/': typeof AppOrganizationInvestigationsIndexRoute
  '/_app/organization/sources/': typeof AppOrganizationSourcesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forbidden'
    | '/login'
    | '/onboarding'
    | '/sign-up'
    | '/waitlist'
    | '/$'
    | '/activity'
    | '/management'
    | '/organization'
    | '/profile'
    | '/settings'
    | '/workflows'
    | '/onboarding/memory'
    | '/onboarding/workspace'
    | '/onboarding/'
    | '/management/access'
    | '/management/members'
    | '/management/permissions'
    | '/organization/integrations'
    | '/organization/investigations'
    | '/organization/memory'
    | '/organization/sources'
    | '/organization/units'
    | '/settings/documentation'
    | '/settings/notifications'
    | '/settings/workspace'
    | '/workflows/$workflowId'
    | '/workflows/blueprints'
    | '/workflows/memory'
    | '/workflows/new'
    | '/workflows/runs'
    | '/workflows/templates'
    | '/organization/'
    | '/settings/'
    | '/workflows/'
    | '/management/members/$memberId'
    | '/organization/integrations/$integrationId'
    | '/organization/integrations/catalog'
    | '/organization/integrations/new'
    | '/organization/investigations/$investigationId'
    | '/organization/investigations/new'
    | '/organization/sources/$sourceId'
    | '/organization/sources/new'
    | '/organization/units/new'
    | '/workflows/blueprints/$blueprintId'
    | '/workflows/definitions/$workflowId'
    | '/workflows/memory/add'
    | '/management/members/'
    | '/organization/integrations/'
    | '/organization/investigations/'
    | '/organization/sources/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forbidden'
    | '/login'
    | '/sign-up'
    | '/waitlist'
    | '/$'
    | '/activity'
    | '/management'
    | '/profile'
    | '/onboarding/memory'
    | '/onboarding/workspace'
    | '/'
    | '/onboarding'
    | '/management/access'
    | '/management/permissions'
    | '/organization/memory'
    | '/organization/units'
    | '/settings/documentation'
    | '/settings/notifications'
    | '/settings/workspace'
    | '/workflows/$workflowId'
    | '/workflows/blueprints'
    | '/workflows/memory'
    | '/workflows/new'
    | '/workflows/runs'
    | '/workflows/templates'
    | '/organization'
    | '/settings'
    | '/workflows'
    | '/management/members/$memberId'
    | '/organization/integrations/$integrationId'
    | '/organization/integrations/catalog'
    | '/organization/integrations/new'
    | '/organization/investigations/$investigationId'
    | '/organization/investigations/new'
    | '/organization/sources/$sourceId'
    | '/organization/sources/new'
    | '/organization/units/new'
    | '/workflows/blueprints/$blueprintId'
    | '/workflows/definitions/$workflowId'
    | '/workflows/memory/add'
    | '/management/members'
    | '/organization/integrations'
    | '/organization/investigations'
    | '/organization/sources'
  id:
    | '__root__'
    | '/_app'
    | '/forbidden'
    | '/login'
    | '/onboarding'
    | '/sign-up'
    | '/waitlist'
    | '/_app/$'
    | '/_app/activity'
    | '/_app/management'
    | '/_app/organization'
    | '/_app/profile'
    | '/_app/settings'
    | '/_app/workflows'
    | '/onboarding/memory'
    | '/onboarding/workspace'
    | '/_app/'
    | '/onboarding/'
    | '/_app/management/access'
    | '/_app/management/members'
    | '/_app/management/permissions'
    | '/_app/organization/integrations'
    | '/_app/organization/investigations'
    | '/_app/organization/memory'
    | '/_app/organization/sources'
    | '/_app/organization/units'
    | '/_app/settings/documentation'
    | '/_app/settings/notifications'
    | '/_app/settings/workspace'
    | '/_app/workflows/$workflowId'
    | '/_app/workflows/blueprints'
    | '/_app/workflows/memory'
    | '/_app/workflows/new'
    | '/_app/workflows/runs'
    | '/_app/workflows/templates'
    | '/_app/organization/'
    | '/_app/settings/'
    | '/_app/workflows/'
    | '/_app/management/members/$memberId'
    | '/_app/organization/integrations/$integrationId'
    | '/_app/organization/integrations/catalog'
    | '/_app/organization/integrations/new'
    | '/_app/organization/investigations/$investigationId'
    | '/_app/organization/investigations/new'
    | '/_app/organization/sources/$sourceId'
    | '/_app/organization/sources/new'
    | '/_app/organization/units/new'
    | '/_app/workflows/blueprints/$blueprintId'
    | '/_app/workflows/definitions/$workflowId'
    | '/_app/workflows/memory/add'
    | '/_app/management/members/'
    | '/_app/organization/integrations/'
    | '/_app/organization/investigations/'
    | '/_app/organization/sources/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ForbiddenRoute: typeof ForbiddenRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRouteWithChildren
  SignUpRoute: typeof SignUpRoute
  WaitlistRoute: typeof WaitlistRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waitlist': {
      id: '/waitlist'
      path: '/waitlist'
      fullPath: '/waitlist'
      preLoaderRoute: typeof WaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$': {
      id: '/_app/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof AppSplatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/activity': {
      id: '/_app/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/management': {
      id: '/_app/management'
      path: '/management'
      fullPath: '/management'
      preLoaderRoute: typeof AppManagementRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organization': {
      id: '/_app/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof AppOrganizationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workflows': {
      id: '/_app/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof AppWorkflowsRouteImport
      parentRoute: typeof AppRoute
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/memory': {
      id: '/onboarding/memory'
      path: '/memory'
      fullPath: '/onboarding/memory'
      preLoaderRoute: typeof OnboardingMemoryRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/workspace': {
      id: '/onboarding/workspace'
      path: '/workspace'
      fullPath: '/onboarding/workspace'
      preLoaderRoute: typeof OnboardingWorkspaceRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/_app/management/access': {
      id: '/_app/management/access'
      path: '/access'
      fullPath: '/management/access'
      preLoaderRoute: typeof AppManagementAccessRouteImport
      parentRoute: typeof AppManagementRoute
    }
    '/_app/management/members': {
      id: '/_app/management/members'
      path: '/members'
      fullPath: '/management/members'
      preLoaderRoute: typeof AppManagementMembersRouteImport
      parentRoute: typeof AppManagementRoute
    }
    '/_app/management/permissions': {
      id: '/_app/management/permissions'
      path: '/permissions'
      fullPath: '/management/permissions'
      preLoaderRoute: typeof AppManagementPermissionsRouteImport
      parentRoute: typeof AppManagementRoute
    }
    '/_app/organization/': {
      id: '/_app/organization/'
      path: '/'
      fullPath: '/organization/'
      preLoaderRoute: typeof AppOrganizationIndexRouteImport
      parentRoute: typeof AppOrganizationRoute
    }
    '/_app/organization/integrations': {
      id: '/_app/organization/integrations'
      path: '/integrations'
      fullPath: '/organization/integrations'
      preLoaderRoute: typeof AppOrganizationIntegrationsRouteImport
      parentRoute: typeof AppOrganizationRoute
    }
    '/_app/organization/investigations': {
      id: '/_app/organization/investigations'
      path: '/investigations'
      fullPath: '/organization/investigations'
      preLoaderRoute: typeof AppOrganizationInvestigationsRouteImport
      parentRoute: typeof AppOrganizationRoute
    }
    '/_app/organization/memory': {
      id: '/_app/organization/memory'
      path: '/memory'
      fullPath: '/organization/memory'
      preLoaderRoute: typeof AppOrganizationMemoryRouteImport
      parentRoute: typeof AppOrganizationRoute
    }
    '/_app/organization/sources': {
      id: '/_app/organization/sources'
      path: '/sources'
      fullPath: '/organization/sources'
      preLoaderRoute: typeof AppOrganizationSourcesRouteImport
      parentRoute: typeof AppOrganizationRoute
    }
    '/_app/organization/units': {
      id: '/_app/organization/units'
      path: '/units'
      fullPath: '/organization/units'
      preLoaderRoute: typeof AppOrganizationUnitsRouteImport
      parentRoute: typeof AppOrganizationRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/documentation': {
      id: '/_app/settings/documentation'
      path: '/documentation'
      fullPath: '/settings/documentation'
      preLoaderRoute: typeof AppSettingsDocumentationRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/notifications': {
      id: '/_app/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AppSettingsNotificationsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/workspace': {
      id: '/_app/settings/workspace'
      path: '/workspace'
      fullPath: '/settings/workspace'
      preLoaderRoute: typeof AppSettingsWorkspaceRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/workflows/': {
      id: '/_app/workflows/'
      path: '/'
      fullPath: '/workflows/'
      preLoaderRoute: typeof AppWorkflowsIndexRouteImport
      parentRoute: typeof AppWorkflowsRoute
    }
    '/_app/workflows/$workflowId': {
      id: '/_app/workflows/$workflowId'
      path: '/$workflowId'
      fullPath: '/workflows/$workflowId'
      preLoaderRoute: typeof AppWorkflowsWorkflowIdRouteImport
      parentRoute: typeof AppWorkflowsRoute
    }
    '/_app/workflows/blueprints': {
      id: '/_app/workflows/blueprints'
      path: '/blueprints'
      fullPath: '/workflows/blueprints'
      preLoaderRoute: typeof AppWorkflowsBlueprintsRouteImport
      parentRoute: typeof AppWorkflowsRoute
    }
    '/_app/workflows/memory': {
      id: '/_app/workflows/memory'
      path: '/memory'
      fullPath: '/workflows/memory'
      preLoaderRoute: typeof AppWorkflowsMemoryRouteImport
      parentRoute: typeof AppWorkflowsRoute
    }
    '/_app/workflows/new': {
      id: '/_app/workflows/new'
      path: '/new'
      fullPath: '/workflows/new'
      preLoaderRoute: typeof AppWorkflowsNewRouteImport
      parentRoute: typeof AppWorkflowsRoute
    }
    '/_app/workflows/runs': {
      id: '/_app/workflows/runs'
      path: '/runs'
      fullPath: '/workflows/runs'
      preLoaderRoute: typeof AppWorkflowsRunsRouteImport
      parentRoute: typeof AppWorkflowsRoute
    }
    '/_app/workflows/templates': {
      id: '/_app/workflows/templates'
      path: '/templates'
      fullPath: '/workflows/templates'
      preLoaderRoute: typeof AppWorkflowsTemplatesRouteImport
      parentRoute: typeof AppWorkflowsRoute
    }
    '/_app/management/members/': {
      id: '/_app/management/members/'
      path: '/'
      fullPath: '/management/members/'
      preLoaderRoute: typeof AppManagementMembersIndexRouteImport
      parentRoute: typeof AppManagementMembersRoute
    }
    '/_app/management/members/$memberId': {
      id: '/_app/management/members/$memberId'
      path: '/$memberId'
      fullPath: '/management/members/$memberId'
      preLoaderRoute: typeof AppManagementMembersMemberIdRouteImport
      parentRoute: typeof AppManagementMembersRoute
    }
    '/_app/organization/integrations/': {
      id: '/_app/organization/integrations/'
      path: '/'
      fullPath: '/organization/integrations/'
      preLoaderRoute: typeof AppOrganizationIntegrationsIndexRouteImport
      parentRoute: typeof AppOrganizationIntegrationsRoute
    }
    '/_app/organization/integrations/$integrationId': {
      id: '/_app/organization/integrations/$integrationId'
      path: '/$integrationId'
      fullPath: '/organization/integrations/$integrationId'
      preLoaderRoute: typeof AppOrganizationIntegrationsIntegrationIdRouteImport
      parentRoute: typeof AppOrganizationIntegrationsRoute
    }
    '/_app/organization/integrations/catalog': {
      id: '/_app/organization/integrations/catalog'
      path: '/catalog'
      fullPath: '/organization/integrations/catalog'
      preLoaderRoute: typeof AppOrganizationIntegrationsCatalogRouteImport
      parentRoute: typeof AppOrganizationIntegrationsRoute
    }
    '/_app/organization/integrations/new': {
      id: '/_app/organization/integrations/new'
      path: '/new'
      fullPath: '/organization/integrations/new'
      preLoaderRoute: typeof AppOrganizationIntegrationsNewRouteImport
      parentRoute: typeof AppOrganizationIntegrationsRoute
    }
    '/_app/organization/investigations/': {
      id: '/_app/organization/investigations/'
      path: '/'
      fullPath: '/organization/investigations/'
      preLoaderRoute: typeof AppOrganizationInvestigationsIndexRouteImport
      parentRoute: typeof AppOrganizationInvestigationsRoute
    }
    '/_app/organization/investigations/$investigationId': {
      id: '/_app/organization/investigations/$investigationId'
      path: '/$investigationId'
      fullPath: '/organization/investigations/$investigationId'
      preLoaderRoute: typeof AppOrganizationInvestigationsInvestigationIdRouteImport
      parentRoute: typeof AppOrganizationInvestigationsRoute
    }
    '/_app/organization/investigations/new': {
      id: '/_app/organization/investigations/new'
      path: '/new'
      fullPath: '/organization/investigations/new'
      preLoaderRoute: typeof AppOrganizationInvestigationsNewRouteImport
      parentRoute: typeof AppOrganizationInvestigationsRoute
    }
    '/_app/organization/sources/': {
      id: '/_app/organization/sources/'
      path: '/'
      fullPath: '/organization/sources/'
      preLoaderRoute: typeof AppOrganizationSourcesIndexRouteImport
      parentRoute: typeof AppOrganizationSourcesRoute
    }
    '/_app/organization/sources/$sourceId': {
      id: '/_app/organization/sources/$sourceId'
      path: '/$sourceId'
      fullPath: '/organization/sources/$sourceId'
      preLoaderRoute: typeof AppOrganizationSourcesSourceIdRouteImport
      parentRoute: typeof AppOrganizationSourcesRoute
    }
    '/_app/organization/sources/new': {
      id: '/_app/organization/sources/new'
      path: '/new'
      fullPath: '/organization/sources/new'
      preLoaderRoute: typeof AppOrganizationSourcesNewRouteImport
      parentRoute: typeof AppOrganizationSourcesRoute
    }
    '/_app/organization/units/new': {
      id: '/_app/organization/units/new'
      path: '/new'
      fullPath: '/organization/units/new'
      preLoaderRoute: typeof AppOrganizationUnitsNewRouteImport
      parentRoute: typeof AppOrganizationUnitsRoute
    }
    '/_app/workflows/blueprints/$blueprintId': {
      id: '/_app/workflows/blueprints/$blueprintId'
      path: '/$blueprintId'
      fullPath: '/workflows/blueprints/$blueprintId'
      preLoaderRoute: typeof AppWorkflowsBlueprintsBlueprintIdRouteImport
      parentRoute: typeof AppWorkflowsBlueprintsRoute
    }
    '/_app/workflows/definitions/$workflowId': {
      id: '/_app/workflows/definitions/$workflowId'
      path: '/definitions/$workflowId'
      fullPath: '/workflows/definitions/$workflowId'
      preLoaderRoute: typeof AppWorkflowsDefinitionsWorkflowIdRouteImport
      parentRoute: typeof AppWorkflowsRoute
    }
    '/_app/workflows/memory/add': {
      id: '/_app/workflows/memory/add'
      path: '/add'
      fullPath: '/workflows/memory/add'
      preLoaderRoute: typeof AppWorkflowsMemoryAddRouteImport
      parentRoute: typeof AppWorkflowsMemoryRoute
    }
  }
}

interface AppManagementMembersRouteChildren {
  AppManagementMembersMemberIdRoute: typeof AppManagementMembersMemberIdRoute
  AppManagementMembersIndexRoute: typeof AppManagementMembersIndexRoute
}

const AppManagementMembersRouteChildren: AppManagementMembersRouteChildren = {
  AppManagementMembersMemberIdRoute: AppManagementMembersMemberIdRoute,
  AppManagementMembersIndexRoute: AppManagementMembersIndexRoute,
}

const AppManagementMembersRouteWithChildren =
  AppManagementMembersRoute._addFileChildren(AppManagementMembersRouteChildren)

interface AppManagementRouteChildren {
  AppManagementAccessRoute: typeof AppManagementAccessRoute
  AppManagementMembersRoute: typeof AppManagementMembersRouteWithChildren
  AppManagementPermissionsRoute: typeof AppManagementPermissionsRoute
}

const AppManagementRouteChildren: AppManagementRouteChildren = {
  AppManagementAccessRoute: AppManagementAccessRoute,
  AppManagementMembersRoute: AppManagementMembersRouteWithChildren,
  AppManagementPermissionsRoute: AppManagementPermissionsRoute,
}

const AppManagementRouteWithChildren = AppManagementRoute._addFileChildren(
  AppManagementRouteChildren,
)

interface AppOrganizationIntegrationsRouteChildren {
  AppOrganizationIntegrationsIntegrationIdRoute: typeof AppOrganizationIntegrationsIntegrationIdRoute
  AppOrganizationIntegrationsCatalogRoute: typeof AppOrganizationIntegrationsCatalogRoute
  AppOrganizationIntegrationsNewRoute: typeof AppOrganizationIntegrationsNewRoute
  AppOrganizationIntegrationsIndexRoute: typeof AppOrganizationIntegrationsIndexRoute
}

const AppOrganizationIntegrationsRouteChildren: AppOrganizationIntegrationsRouteChildren =
  {
    AppOrganizationIntegrationsIntegrationIdRoute:
      AppOrganizationIntegrationsIntegrationIdRoute,
    AppOrganizationIntegrationsCatalogRoute:
      AppOrganizationIntegrationsCatalogRoute,
    AppOrganizationIntegrationsNewRoute: AppOrganizationIntegrationsNewRoute,
    AppOrganizationIntegrationsIndexRoute:
      AppOrganizationIntegrationsIndexRoute,
  }

const AppOrganizationIntegrationsRouteWithChildren =
  AppOrganizationIntegrationsRoute._addFileChildren(
    AppOrganizationIntegrationsRouteChildren,
  )

interface AppOrganizationInvestigationsRouteChildren {
  AppOrganizationInvestigationsInvestigationIdRoute: typeof AppOrganizationInvestigationsInvestigationIdRoute
  AppOrganizationInvestigationsNewRoute: typeof AppOrganizationInvestigationsNewRoute
  AppOrganizationInvestigationsIndexRoute: typeof AppOrganizationInvestigationsIndexRoute
}

const AppOrganizationInvestigationsRouteChildren: AppOrganizationInvestigationsRouteChildren =
  {
    AppOrganizationInvestigationsInvestigationIdRoute:
      AppOrganizationInvestigationsInvestigationIdRoute,
    AppOrganizationInvestigationsNewRoute:
      AppOrganizationInvestigationsNewRoute,
    AppOrganizationInvestigationsIndexRoute:
      AppOrganizationInvestigationsIndexRoute,
  }

const AppOrganizationInvestigationsRouteWithChildren =
  AppOrganizationInvestigationsRoute._addFileChildren(
    AppOrganizationInvestigationsRouteChildren,
  )

interface AppOrganizationSourcesRouteChildren {
  AppOrganizationSourcesSourceIdRoute: typeof AppOrganizationSourcesSourceIdRoute
  AppOrganizationSourcesNewRoute: typeof AppOrganizationSourcesNewRoute
  AppOrganizationSourcesIndexRoute: typeof AppOrganizationSourcesIndexRoute
}

const AppOrganizationSourcesRouteChildren: AppOrganizationSourcesRouteChildren =
  {
    AppOrganizationSourcesSourceIdRoute: AppOrganizationSourcesSourceIdRoute,
    AppOrganizationSourcesNewRoute: AppOrganizationSourcesNewRoute,
    AppOrganizationSourcesIndexRoute: AppOrganizationSourcesIndexRoute,
  }

const AppOrganizationSourcesRouteWithChildren =
  AppOrganizationSourcesRoute._addFileChildren(
    AppOrganizationSourcesRouteChildren,
  )

interface AppOrganizationUnitsRouteChildren {
  AppOrganizationUnitsNewRoute: typeof AppOrganizationUnitsNewRoute
}

const AppOrganizationUnitsRouteChildren: AppOrganizationUnitsRouteChildren = {
  AppOrganizationUnitsNewRoute: AppOrganizationUnitsNewRoute,
}

const AppOrganizationUnitsRouteWithChildren =
  AppOrganizationUnitsRoute._addFileChildren(AppOrganizationUnitsRouteChildren)

interface AppOrganizationRouteChildren {
  AppOrganizationIntegrationsRoute: typeof AppOrganizationIntegrationsRouteWithChildren
  AppOrganizationInvestigationsRoute: typeof AppOrganizationInvestigationsRouteWithChildren
  AppOrganizationMemoryRoute: typeof AppOrganizationMemoryRoute
  AppOrganizationSourcesRoute: typeof AppOrganizationSourcesRouteWithChildren
  AppOrganizationUnitsRoute: typeof AppOrganizationUnitsRouteWithChildren
  AppOrganizationIndexRoute: typeof AppOrganizationIndexRoute
}

const AppOrganizationRouteChildren: AppOrganizationRouteChildren = {
  AppOrganizationIntegrationsRoute:
    AppOrganizationIntegrationsRouteWithChildren,
  AppOrganizationInvestigationsRoute:
    AppOrganizationInvestigationsRouteWithChildren,
  AppOrganizationMemoryRoute: AppOrganizationMemoryRoute,
  AppOrganizationSourcesRoute: AppOrganizationSourcesRouteWithChildren,
  AppOrganizationUnitsRoute: AppOrganizationUnitsRouteWithChildren,
  AppOrganizationIndexRoute: AppOrganizationIndexRoute,
}

const AppOrganizationRouteWithChildren = AppOrganizationRoute._addFileChildren(
  AppOrganizationRouteChildren,
)

interface AppSettingsRouteChildren {
  AppSettingsDocumentationRoute: typeof AppSettingsDocumentationRoute
  AppSettingsNotificationsRoute: typeof AppSettingsNotificationsRoute
  AppSettingsWorkspaceRoute: typeof AppSettingsWorkspaceRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsDocumentationRoute: AppSettingsDocumentationRoute,
  AppSettingsNotificationsRoute: AppSettingsNotificationsRoute,
  AppSettingsWorkspaceRoute: AppSettingsWorkspaceRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppWorkflowsBlueprintsRouteChildren {
  AppWorkflowsBlueprintsBlueprintIdRoute: typeof AppWorkflowsBlueprintsBlueprintIdRoute
}

const AppWorkflowsBlueprintsRouteChildren: AppWorkflowsBlueprintsRouteChildren =
  {
    AppWorkflowsBlueprintsBlueprintIdRoute:
      AppWorkflowsBlueprintsBlueprintIdRoute,
  }

const AppWorkflowsBlueprintsRouteWithChildren =
  AppWorkflowsBlueprintsRoute._addFileChildren(
    AppWorkflowsBlueprintsRouteChildren,
  )

interface AppWorkflowsMemoryRouteChildren {
  AppWorkflowsMemoryAddRoute: typeof AppWorkflowsMemoryAddRoute
}

const AppWorkflowsMemoryRouteChildren: AppWorkflowsMemoryRouteChildren = {
  AppWorkflowsMemoryAddRoute: AppWorkflowsMemoryAddRoute,
}

const AppWorkflowsMemoryRouteWithChildren =
  AppWorkflowsMemoryRoute._addFileChildren(AppWorkflowsMemoryRouteChildren)

interface AppWorkflowsRouteChildren {
  AppWorkflowsWorkflowIdRoute: typeof AppWorkflowsWorkflowIdRoute
  AppWorkflowsBlueprintsRoute: typeof AppWorkflowsBlueprintsRouteWithChildren
  AppWorkflowsMemoryRoute: typeof AppWorkflowsMemoryRouteWithChildren
  AppWorkflowsNewRoute: typeof AppWorkflowsNewRoute
  AppWorkflowsRunsRoute: typeof AppWorkflowsRunsRoute
  AppWorkflowsTemplatesRoute: typeof AppWorkflowsTemplatesRoute
  AppWorkflowsIndexRoute: typeof AppWorkflowsIndexRoute
  AppWorkflowsDefinitionsWorkflowIdRoute: typeof AppWorkflowsDefinitionsWorkflowIdRoute
}

const AppWorkflowsRouteChildren: AppWorkflowsRouteChildren = {
  AppWorkflowsWorkflowIdRoute: AppWorkflowsWorkflowIdRoute,
  AppWorkflowsBlueprintsRoute: AppWorkflowsBlueprintsRouteWithChildren,
  AppWorkflowsMemoryRoute: AppWorkflowsMemoryRouteWithChildren,
  AppWorkflowsNewRoute: AppWorkflowsNewRoute,
  AppWorkflowsRunsRoute: AppWorkflowsRunsRoute,
  AppWorkflowsTemplatesRoute: AppWorkflowsTemplatesRoute,
  AppWorkflowsIndexRoute: AppWorkflowsIndexRoute,
  AppWorkflowsDefinitionsWorkflowIdRoute:
    AppWorkflowsDefinitionsWorkflowIdRoute,
}

const AppWorkflowsRouteWithChildren = AppWorkflowsRoute._addFileChildren(
  AppWorkflowsRouteChildren,
)

interface AppRouteChildren {
  AppSplatRoute: typeof AppSplatRoute
  AppActivityRoute: typeof AppActivityRoute
  AppManagementRoute: typeof AppManagementRouteWithChildren
  AppOrganizationRoute: typeof AppOrganizationRouteWithChildren
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppWorkflowsRoute: typeof AppWorkflowsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSplatRoute: AppSplatRoute,
  AppActivityRoute: AppActivityRoute,
  AppManagementRoute: AppManagementRouteWithChildren,
  AppOrganizationRoute: AppOrganizationRouteWithChildren,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppWorkflowsRoute: AppWorkflowsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface OnboardingRouteChildren {
  OnboardingMemoryRoute: typeof OnboardingMemoryRoute
  OnboardingWorkspaceRoute: typeof OnboardingWorkspaceRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingMemoryRoute: OnboardingMemoryRoute,
  OnboardingWorkspaceRoute: OnboardingWorkspaceRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ForbiddenRoute: ForbiddenRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRouteWithChildren,
  SignUpRoute: SignUpRoute,
  WaitlistRoute: WaitlistRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
