/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppIntegrationsRouteImport } from './routes/_app/integrations'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppWorkflowsRouteImport } from './routes/_app/workflows'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as OnboardingCoordinationRouteImport } from './routes/onboarding/coordination'
import { Route as OnboardingMemoryRouteImport } from './routes/onboarding/memory'
import { Route as OnboardingWorkflowsRouteImport } from './routes/onboarding/workflows'
import { Route as OnboardingWorkspaceRouteImport } from './routes/onboarding/workspace'
import { Route as AppIntegrationsIndexRouteImport } from './routes/_app/integrations/index'
import { Route as AppIntegrationsIntegrationIdRouteImport } from './routes/_app/integrations/$integrationId'
import { Route as AppIntegrationsNewRouteImport } from './routes/_app/integrations/new'
import { Route as AppWorkflowsIndexRouteImport } from './routes/_app/workflows/index'
import { Route as AppWorkflowsWorkflowIdRouteImport } from './routes/_app/workflows/$workflowId'
import { Route as AppWorkflowsNewRouteImport } from './routes/_app/workflows/new'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsRoute = AppIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkflowsRoute = AppWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => AppRoute,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingCoordinationRoute = OnboardingCoordinationRouteImport.update({
  id: '/coordination',
  path: '/coordination',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingMemoryRoute = OnboardingMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingWorkflowsRoute = OnboardingWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingWorkspaceRoute = OnboardingWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => OnboardingRoute,
} as any)
const AppIntegrationsIndexRoute = AppIntegrationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppIntegrationsRoute,
} as any)
const AppIntegrationsIntegrationIdRoute =
  AppIntegrationsIntegrationIdRouteImport.update({
    id: '/$integrationId',
    path: '/$integrationId',
    getParentRoute: () => AppIntegrationsRoute,
  } as any)
const AppIntegrationsNewRoute = AppIntegrationsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppIntegrationsRoute,
} as any)
const AppWorkflowsIndexRoute = AppWorkflowsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppWorkflowsRoute,
} as any)
const AppWorkflowsWorkflowIdRoute = AppWorkflowsWorkflowIdRouteImport.update({
  id: '/$workflowId',
  path: '/$workflowId',
  getParentRoute: () => AppWorkflowsRoute,
} as any)
const AppWorkflowsNewRoute = AppWorkflowsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppWorkflowsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/sign-up': typeof SignUpRoute
  '/integrations': typeof AppIntegrationsRouteWithChildren
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/workflows': typeof AppWorkflowsRouteWithChildren
  '/onboarding/coordination': typeof OnboardingCoordinationRoute
  '/onboarding/memory': typeof OnboardingMemoryRoute
  '/onboarding/workflows': typeof OnboardingWorkflowsRoute
  '/onboarding/workspace': typeof OnboardingWorkspaceRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/integrations/$integrationId': typeof AppIntegrationsIntegrationIdRoute
  '/integrations/new': typeof AppIntegrationsNewRoute
  '/workflows/$workflowId': typeof AppWorkflowsWorkflowIdRoute
  '/workflows/new': typeof AppWorkflowsNewRoute
  '/integrations/': typeof AppIntegrationsIndexRoute
  '/workflows/': typeof AppWorkflowsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/sign-up': typeof SignUpRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/onboarding/coordination': typeof OnboardingCoordinationRoute
  '/onboarding/memory': typeof OnboardingMemoryRoute
  '/onboarding/workflows': typeof OnboardingWorkflowsRoute
  '/onboarding/workspace': typeof OnboardingWorkspaceRoute
  '/': typeof AppIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/integrations/$integrationId': typeof AppIntegrationsIntegrationIdRoute
  '/integrations/new': typeof AppIntegrationsNewRoute
  '/workflows/$workflowId': typeof AppWorkflowsWorkflowIdRoute
  '/workflows/new': typeof AppWorkflowsNewRoute
  '/integrations': typeof AppIntegrationsIndexRoute
  '/workflows': typeof AppWorkflowsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/sign-up': typeof SignUpRoute
  '/_app/integrations': typeof AppIntegrationsRouteWithChildren
  '/_app/profile': typeof AppProfileRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/workflows': typeof AppWorkflowsRouteWithChildren
  '/onboarding/coordination': typeof OnboardingCoordinationRoute
  '/onboarding/memory': typeof OnboardingMemoryRoute
  '/onboarding/workflows': typeof OnboardingWorkflowsRoute
  '/onboarding/workspace': typeof OnboardingWorkspaceRoute
  '/_app/': typeof AppIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/_app/integrations/$integrationId': typeof AppIntegrationsIntegrationIdRoute
  '/_app/integrations/new': typeof AppIntegrationsNewRoute
  '/_app/workflows/$workflowId': typeof AppWorkflowsWorkflowIdRoute
  '/_app/workflows/new': typeof AppWorkflowsNewRoute
  '/_app/integrations/': typeof AppIntegrationsIndexRoute
  '/_app/workflows/': typeof AppWorkflowsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/sign-up'
    | '/integrations'
    | '/profile'
    | '/settings'
    | '/workflows'
    | '/onboarding/coordination'
    | '/onboarding/memory'
    | '/onboarding/workflows'
    | '/onboarding/workspace'
    | '/onboarding/'
    | '/integrations/$integrationId'
    | '/integrations/new'
    | '/workflows/$workflowId'
    | '/workflows/new'
    | '/integrations/'
    | '/workflows/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/sign-up'
    | '/profile'
    | '/settings'
    | '/onboarding/coordination'
    | '/onboarding/memory'
    | '/onboarding/workflows'
    | '/onboarding/workspace'
    | '/'
    | '/onboarding'
    | '/integrations/$integrationId'
    | '/integrations/new'
    | '/workflows/$workflowId'
    | '/workflows/new'
    | '/integrations'
    | '/workflows'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/onboarding'
    | '/sign-up'
    | '/_app/integrations'
    | '/_app/profile'
    | '/_app/settings'
    | '/_app/workflows'
    | '/onboarding/coordination'
    | '/onboarding/memory'
    | '/onboarding/workflows'
    | '/onboarding/workspace'
    | '/_app/'
    | '/onboarding/'
    | '/_app/integrations/$integrationId'
    | '/_app/integrations/new'
    | '/_app/workflows/$workflowId'
    | '/_app/workflows/new'
    | '/_app/integrations/'
    | '/_app/workflows/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRouteWithChildren
  SignUpRoute: typeof SignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrations': {
      id: '/_app/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AppIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workflows': {
      id: '/_app/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof AppWorkflowsRouteImport
      parentRoute: typeof AppRoute
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/coordination': {
      id: '/onboarding/coordination'
      path: '/coordination'
      fullPath: '/onboarding/coordination'
      preLoaderRoute: typeof OnboardingCoordinationRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/memory': {
      id: '/onboarding/memory'
      path: '/memory'
      fullPath: '/onboarding/memory'
      preLoaderRoute: typeof OnboardingMemoryRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/workflows': {
      id: '/onboarding/workflows'
      path: '/workflows'
      fullPath: '/onboarding/workflows'
      preLoaderRoute: typeof OnboardingWorkflowsRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/workspace': {
      id: '/onboarding/workspace'
      path: '/workspace'
      fullPath: '/onboarding/workspace'
      preLoaderRoute: typeof OnboardingWorkspaceRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/_app/integrations/': {
      id: '/_app/integrations/'
      path: '/'
      fullPath: '/integrations/'
      preLoaderRoute: typeof AppIntegrationsIndexRouteImport
      parentRoute: typeof AppIntegrationsRoute
    }
    '/_app/integrations/$integrationId': {
      id: '/_app/integrations/$integrationId'
      path: '/$integrationId'
      fullPath: '/integrations/$integrationId'
      preLoaderRoute: typeof AppIntegrationsIntegrationIdRouteImport
      parentRoute: typeof AppIntegrationsRoute
    }
    '/_app/integrations/new': {
      id: '/_app/integrations/new'
      path: '/new'
      fullPath: '/integrations/new'
      preLoaderRoute: typeof AppIntegrationsNewRouteImport
      parentRoute: typeof AppIntegrationsRoute
    }
    '/_app/workflows/': {
      id: '/_app/workflows/'
      path: '/'
      fullPath: '/workflows/'
      preLoaderRoute: typeof AppWorkflowsIndexRouteImport
      parentRoute: typeof AppWorkflowsRoute
    }
    '/_app/workflows/$workflowId': {
      id: '/_app/workflows/$workflowId'
      path: '/$workflowId'
      fullPath: '/workflows/$workflowId'
      preLoaderRoute: typeof AppWorkflowsWorkflowIdRouteImport
      parentRoute: typeof AppWorkflowsRoute
    }
    '/_app/workflows/new': {
      id: '/_app/workflows/new'
      path: '/new'
      fullPath: '/workflows/new'
      preLoaderRoute: typeof AppWorkflowsNewRouteImport
      parentRoute: typeof AppWorkflowsRoute
    }
  }
}

interface AppIntegrationsRouteChildren {
  AppIntegrationsIntegrationIdRoute: typeof AppIntegrationsIntegrationIdRoute
  AppIntegrationsNewRoute: typeof AppIntegrationsNewRoute
  AppIntegrationsIndexRoute: typeof AppIntegrationsIndexRoute
}

const AppIntegrationsRouteChildren: AppIntegrationsRouteChildren = {
  AppIntegrationsIntegrationIdRoute: AppIntegrationsIntegrationIdRoute,
  AppIntegrationsNewRoute: AppIntegrationsNewRoute,
  AppIntegrationsIndexRoute: AppIntegrationsIndexRoute,
}

const AppIntegrationsRouteWithChildren = AppIntegrationsRoute._addFileChildren(
  AppIntegrationsRouteChildren,
)

interface AppWorkflowsRouteChildren {
  AppWorkflowsWorkflowIdRoute: typeof AppWorkflowsWorkflowIdRoute
  AppWorkflowsNewRoute: typeof AppWorkflowsNewRoute
  AppWorkflowsIndexRoute: typeof AppWorkflowsIndexRoute
}

const AppWorkflowsRouteChildren: AppWorkflowsRouteChildren = {
  AppWorkflowsWorkflowIdRoute: AppWorkflowsWorkflowIdRoute,
  AppWorkflowsNewRoute: AppWorkflowsNewRoute,
  AppWorkflowsIndexRoute: AppWorkflowsIndexRoute,
}

const AppWorkflowsRouteWithChildren = AppWorkflowsRoute._addFileChildren(
  AppWorkflowsRouteChildren,
)

interface AppRouteChildren {
  AppIntegrationsRoute: typeof AppIntegrationsRouteWithChildren
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppWorkflowsRoute: typeof AppWorkflowsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIntegrationsRoute: AppIntegrationsRouteWithChildren,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppWorkflowsRoute: AppWorkflowsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface OnboardingRouteChildren {
  OnboardingCoordinationRoute: typeof OnboardingCoordinationRoute
  OnboardingMemoryRoute: typeof OnboardingMemoryRoute
  OnboardingWorkflowsRoute: typeof OnboardingWorkflowsRoute
  OnboardingWorkspaceRoute: typeof OnboardingWorkspaceRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingCoordinationRoute: OnboardingCoordinationRoute,
  OnboardingMemoryRoute: OnboardingMemoryRoute,
  OnboardingWorkflowsRoute: OnboardingWorkflowsRoute,
  OnboardingWorkspaceRoute: OnboardingWorkspaceRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRouteWithChildren,
  SignUpRoute: SignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
