// Code generated by scripts/generate-permissions.mjs. DO NOT EDIT.

package contracts

// Permission identifies a server capability shared across API and UI contracts.
type Permission string

const (
	PermissionOnboardingManage Permission = "onboarding:manage"
	PermissionWorkflowsRead Permission = "workflows:read"
	PermissionWorkflowsRun Permission = "workflows:run"
	PermissionWorkflowsManage Permission = "workflows:manage"
	PermissionIntegrationsRead Permission = "integrations:read"
	PermissionIntegrationsManage Permission = "integrations:manage"
	PermissionKnowledgeRead Permission = "knowledge:read"
	PermissionKnowledgeManage Permission = "knowledge:manage"
	PermissionOrganizationRead Permission = "organization:read"
	PermissionOrganizationManage Permission = "organization:manage"
	PermissionSettingsRead Permission = "settings:read"
	PermissionSettingsManage Permission = "settings:manage"
)

var AllPermissions = []Permission{
	PermissionOnboardingManage,
	PermissionWorkflowsRead,
	PermissionWorkflowsRun,
	PermissionWorkflowsManage,
	PermissionIntegrationsRead,
	PermissionIntegrationsManage,
	PermissionKnowledgeRead,
	PermissionKnowledgeManage,
	PermissionOrganizationRead,
	PermissionOrganizationManage,
	PermissionSettingsRead,
	PermissionSettingsManage,
}
